#include "nit.common.h"
extern const int COLOR_nit__astbuilder__ASTBuilder___mmodule;
extern const char FILE_nit__astbuilder[];
extern const int COLOR_nit__astbuilder__ASTBuilder___anchor;
val* NEW_nit__ADecIntExpr(const struct type* type);
extern const struct type type_nit__ADecIntExpr;
extern const int COLOR_nit__astbuilder__ASTBuilder__mmodule;
extern const int COLOR_nit__model__MModule__int_type;
extern const int COLOR_nit__astbuilder__ADecIntExpr__make;
val* NEW_nit__ANewExpr(const struct type* type);
extern const struct type type_nit__ANewExpr;
extern const int COLOR_nit__astbuilder__ANewExpr__make;
val* NEW_nit__ACallExpr(const struct type* type);
extern const struct type type_nit__ACallExpr;
extern const int COLOR_nit__astbuilder__ACallExpr__make;
val* NEW_nit__ABlockExpr(const struct type* type);
extern const struct type type_nit__ABlockExpr;
extern const int COLOR_nit__astbuilder__ABlockExpr__make;
val* NEW_nit__ALoopExpr(const struct type* type);
extern const struct type type_nit__ALoopExpr;
extern const int COLOR_nit__astbuilder__ALoopExpr__make;
val* NEW_nit__AVarExpr(const struct type* type);
extern const struct type type_nit__AVarExpr;
extern const int COLOR_nit__astbuilder__AVarExpr__make;
val* NEW_nit__AVarAssignExpr(const struct type* type);
extern const struct type type_nit__AVarAssignExpr;
extern const int COLOR_nit__astbuilder__AVarAssignExpr__make;
extern const int COLOR_nit__model__MProperty__intro;
extern const int COLOR_nit__model__MAttributeDef__static_mtype;
extern const int COLOR_nit__typing__AExpr__mtype;
extern const int COLOR_nit__astbuilder__ASTBuilder__anchor;
extern const int COLOR_nit__model__MType__resolve_for;
val* NEW_nit__AAttrExpr(const struct type* type);
extern const struct type type_nit__AAttrExpr;
extern const int COLOR_nit__astbuilder__AAttrExpr__make;
val* NEW_nit__AAttrAssignExpr(const struct type* type);
extern const struct type type_nit__AAttrAssignExpr;
extern const int COLOR_nit__astbuilder__AAttrAssignExpr__make;
val* NEW_nit__ADoExpr(const struct type* type);
extern const struct type type_nit__ADoExpr;
extern const int COLOR_nit__astbuilder__ADoExpr__make;
val* NEW_nit__ABreakExpr(const struct type* type);
extern const struct type type_nit__ABreakExpr;
extern const int COLOR_nit__astbuilder__ABreakExpr__make;
val* NEW_nit__AIfExpr(const struct type* type);
extern const struct type type_nit__AIfExpr;
extern const int COLOR_nit__astbuilder__AIfExpr__make;
extern const int COLOR_nit___nit__ASTBuilder___standard__kernel__Object__init;
extern const int COLOR_nit__astbuilder__AExpr__variable_cache;
extern const int COLOR_standard__kernel__Object___61d_61d;
extern const int COLOR_nit__parser_nodes__ANode__parent;
extern const int COLOR_standard__kernel__Object___33d_61d;
extern const int COLOR_nit__astbuilder__AExpr__detach_with_placeholder;
val* NEW_nit__Variable(const struct type* type);
extern const struct type type_nit__Variable;
val* standard___standard__NativeString___to_s_with_length(char* self, long p0);
extern const int COLOR_nit__scope__Variable__name_61d;
extern const int COLOR_standard__kernel__Object__init;
extern const int COLOR_nit__typing__Variable__declared_type_61d;
extern const int COLOR_nit__parser_nodes__ANode__replace_with;
extern const int COLOR_nit__astbuilder__AExpr__variable_cache_61d;
extern const int COLOR_nit__typing__Variable__declared_type;
extern const int COLOR_nit__astbuilder__AExpr___variable_cache;
val* NEW_nit__APlaceholderExpr(const struct type* type);
extern const struct type type_nit__APlaceholderExpr;
extern const int COLOR_nit__astbuilder__APlaceholderExpr__make;
val* NEW_standard__NativeArray(int length, const struct type* type);
extern const struct type type_standard__NativeArray__standard__String;
extern const int COLOR_standard__string__Object__inspect;
extern const int COLOR_standard__string__NativeArray__native_to_s;
extern const int COLOR_standard__file__Sys__print;
extern const int COLOR_nit__typing__AExpr__is_typed_61d;
extern const int COLOR_nit__parser_nodes__ABlockExpr__n_expr;
extern const int COLOR_standard__abstract_collection__SimpleCollection__add;
val* NEW_nit__TKwloop(const struct type* type);
extern const struct type type_nit__TKwloop;
extern const int COLOR_nit__parser_nodes__ALoopExpr___n_kwloop;
extern const int COLOR_nit__parser_nodes__ALoopExpr__n_block_61d;
extern const int COLOR_nit__parser_nodes__ALoopExpr__n_block;
extern const int COLOR_nit__astbuilder__AExpr__add;
val* NEW_nit__TKwdo(const struct type* type);
extern const struct type type_nit__TKwdo;
extern const int COLOR_nit__parser_nodes__ADoExpr___n_kwdo;
extern const int COLOR_nit__parser_nodes__ADoExpr__n_block_61d;
extern const int COLOR_nit__parser_nodes__ADoExpr__n_block;
extern const int COLOR_nit__scope__ADoExpr__break_mark;
val* NEW_nit__EscapeMark(const struct type* type);
extern const struct type type_nit__EscapeMark;
extern const int COLOR_nit__scope__EscapeMark__name_61d;
extern const int COLOR_nit__scope__ADoExpr__break_mark_61d;
val* NEW_nit__TKwbreak(const struct type* type);
extern const struct type type_nit__TKwbreak;
extern const int COLOR_nit__parser_nodes__ABreakExpr___n_kwbreak;
extern const int COLOR_nit__scope__AEscapeExpr__escapemark_61d;
extern const int COLOR_nit__scope__EscapeMark__escapes;
val* NEW_nit__TKwif(const struct type* type);
extern const struct type type_nit__TKwif;
extern const int COLOR_nit__parser_nodes__AIfExpr___n_kwif;
extern const int COLOR_nit__parser_nodes__AIfExpr___n_expr;
extern const int COLOR_nit__parser_nodes__ANode__parent_61d;
extern const int COLOR_nit__parser_nodes__AIfExpr___n_then;
extern const int COLOR_nit__parser_nodes__AIfExpr___n_else;
extern const int COLOR_nit__typing__AExpr__mtype_61d;
val* NEW_nit__TClassid(const struct type* type);
extern const struct type type_nit__TClassid;
extern const int COLOR_nit__parser_nodes__AType___n_id;
extern const int COLOR_nit__literal__AIntExpr__value_61d;
val* NEW_nit__TNumber(const struct type* type);
extern const struct type type_nit__TNumber;
extern const int COLOR_nit__parser_nodes__ADecIntExpr___n_number;
val* NEW_nit__TKwnew(const struct type* type);
extern const struct type type_nit__TKwnew;
extern const int COLOR_nit__parser_nodes__ANewExpr___n_kwnew;
val* NEW_nit__AType(const struct type* type);
extern const struct type type_nit__AType;
extern const int COLOR_nit__astbuilder__AType__make;
extern const int COLOR_nit__parser_nodes__ANewExpr___n_type;
val* NEW_nit__AListExprs(const struct type* type);
extern const struct type type_nit__AListExprs;
extern const int COLOR_nit__parser_nodes__ANewExpr___n_args;
extern const int COLOR_nit__parser_nodes__ANewExpr__n_args;
extern const int COLOR_nit__parser_nodes__AExprs__n_exprs;
extern const int COLOR_standard__abstract_collection__SimpleCollection__add_all;
extern const int COLOR_nit__typing__ANewExpr__callsite_61d;
extern const int COLOR_nit__typing__CallSite__recv;
extern const struct type type_nit__MClassType;
extern const int COLOR_nit__typing__ANewExpr__recvtype_61d;
extern const int COLOR_nit__typing__CallSite__mproperty;
extern const int COLOR_nit__model__MMethod__is_new;
extern const int COLOR_nit__typing__CallSite__msignature;
extern const int COLOR_nit__model__MSignature__return_mtype;
extern const int COLOR_nit__parser_nodes__ASendExpr___n_expr;
extern const int COLOR_nit__parser_nodes__ACallFormExpr___n_args;
val* NEW_nit__TId(const struct type* type);
extern const struct type type_nit__TId;
extern const int COLOR_nit__parser_nodes__ACallFormExpr___n_id;
extern const int COLOR_nit__parser_nodes__ACallFormExpr__n_args;
extern const int COLOR_nit__typing__ASendExpr__callsite_61d;
extern const int COLOR_nit__parser_nodes__AAttrFormExpr___n_expr;
val* NEW_nit__TAttrid(const struct type* type);
extern const struct type type_nit__TAttrid;
extern const int COLOR_nit__parser_nodes__AAttrFormExpr___n_id;
extern const int COLOR_nit__typing__AAttrFormExpr__mproperty_61d;
extern const int COLOR_nit__parser_nodes__AAssignFormExpr___n_value;
val* NEW_nit__TAssign(const struct type* type);
extern const struct type type_nit__TAssign;
extern const int COLOR_nit__parser_nodes__AAssignFormExpr___n_assign;
extern const int COLOR_nit__parser_nodes__AVarFormExpr___n_id;
extern const int COLOR_nit__scope__AVarFormExpr__variable_61d;
