#include "nit.common.h"
val* NEW_standard__Array(const struct type* type);
extern const struct type type_standard__Array__nit__parser_work__ReduceAction;
val* NEW_nit__parser__ReduceAction0(const struct type* type);
extern const struct type type_nit__parser__ReduceAction0;
extern const int COLOR_nit__parser_work__ReduceAction__goto_61d;
extern const int COLOR_standard__kernel__Object__init;
val* NEW_nit__parser__ReduceAction1(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1;
val* NEW_nit__parser__ReduceAction2(const struct type* type);
extern const struct type type_nit__parser__ReduceAction2;
val* NEW_nit__parser__ReduceAction3(const struct type* type);
extern const struct type type_nit__parser__ReduceAction3;
val* NEW_nit__parser__ReduceAction4(const struct type* type);
extern const struct type type_nit__parser__ReduceAction4;
val* NEW_nit__parser__ReduceAction5(const struct type* type);
extern const struct type type_nit__parser__ReduceAction5;
val* NEW_nit__parser__ReduceAction6(const struct type* type);
extern const struct type type_nit__parser__ReduceAction6;
val* NEW_nit__parser__ReduceAction7(const struct type* type);
extern const struct type type_nit__parser__ReduceAction7;
val* NEW_nit__parser__ReduceAction8(const struct type* type);
extern const struct type type_nit__parser__ReduceAction8;
val* NEW_nit__parser__ReduceAction9(const struct type* type);
extern const struct type type_nit__parser__ReduceAction9;
val* NEW_nit__parser__ReduceAction10(const struct type* type);
extern const struct type type_nit__parser__ReduceAction10;
val* NEW_nit__parser__ReduceAction11(const struct type* type);
extern const struct type type_nit__parser__ReduceAction11;
val* NEW_nit__parser__ReduceAction12(const struct type* type);
extern const struct type type_nit__parser__ReduceAction12;
val* NEW_nit__parser__ReduceAction13(const struct type* type);
extern const struct type type_nit__parser__ReduceAction13;
val* NEW_nit__parser__ReduceAction14(const struct type* type);
extern const struct type type_nit__parser__ReduceAction14;
val* NEW_nit__parser__ReduceAction15(const struct type* type);
extern const struct type type_nit__parser__ReduceAction15;
val* NEW_nit__parser__ReduceAction16(const struct type* type);
extern const struct type type_nit__parser__ReduceAction16;
val* NEW_nit__parser__ReduceAction17(const struct type* type);
extern const struct type type_nit__parser__ReduceAction17;
val* NEW_nit__parser__ReduceAction18(const struct type* type);
extern const struct type type_nit__parser__ReduceAction18;
val* NEW_nit__parser__ReduceAction19(const struct type* type);
extern const struct type type_nit__parser__ReduceAction19;
val* NEW_nit__parser__ReduceAction20(const struct type* type);
extern const struct type type_nit__parser__ReduceAction20;
val* NEW_nit__parser__ReduceAction21(const struct type* type);
extern const struct type type_nit__parser__ReduceAction21;
val* NEW_nit__parser__ReduceAction22(const struct type* type);
extern const struct type type_nit__parser__ReduceAction22;
val* NEW_nit__parser__ReduceAction23(const struct type* type);
extern const struct type type_nit__parser__ReduceAction23;
val* NEW_nit__parser__ReduceAction24(const struct type* type);
extern const struct type type_nit__parser__ReduceAction24;
val* NEW_nit__parser__ReduceAction26(const struct type* type);
extern const struct type type_nit__parser__ReduceAction26;
val* NEW_nit__parser__ReduceAction27(const struct type* type);
extern const struct type type_nit__parser__ReduceAction27;
val* NEW_nit__parser__ReduceAction29(const struct type* type);
extern const struct type type_nit__parser__ReduceAction29;
val* NEW_nit__parser__ReduceAction30(const struct type* type);
extern const struct type type_nit__parser__ReduceAction30;
val* NEW_nit__parser__ReduceAction31(const struct type* type);
extern const struct type type_nit__parser__ReduceAction31;
val* NEW_nit__parser__ReduceAction32(const struct type* type);
extern const struct type type_nit__parser__ReduceAction32;
val* NEW_nit__parser__ReduceAction33(const struct type* type);
extern const struct type type_nit__parser__ReduceAction33;
val* NEW_nit__parser__ReduceAction34(const struct type* type);
extern const struct type type_nit__parser__ReduceAction34;
val* NEW_nit__parser__ReduceAction35(const struct type* type);
extern const struct type type_nit__parser__ReduceAction35;
val* NEW_nit__parser__ReduceAction36(const struct type* type);
extern const struct type type_nit__parser__ReduceAction36;
val* NEW_nit__parser__ReduceAction37(const struct type* type);
extern const struct type type_nit__parser__ReduceAction37;
val* NEW_nit__parser__ReduceAction38(const struct type* type);
extern const struct type type_nit__parser__ReduceAction38;
val* NEW_nit__parser__ReduceAction39(const struct type* type);
extern const struct type type_nit__parser__ReduceAction39;
val* NEW_nit__parser__ReduceAction40(const struct type* type);
extern const struct type type_nit__parser__ReduceAction40;
val* NEW_nit__parser__ReduceAction41(const struct type* type);
extern const struct type type_nit__parser__ReduceAction41;
val* NEW_nit__parser__ReduceAction42(const struct type* type);
extern const struct type type_nit__parser__ReduceAction42;
val* NEW_nit__parser__ReduceAction43(const struct type* type);
extern const struct type type_nit__parser__ReduceAction43;
val* NEW_nit__parser__ReduceAction44(const struct type* type);
extern const struct type type_nit__parser__ReduceAction44;
val* NEW_nit__parser__ReduceAction45(const struct type* type);
extern const struct type type_nit__parser__ReduceAction45;
val* NEW_nit__parser__ReduceAction46(const struct type* type);
extern const struct type type_nit__parser__ReduceAction46;
val* NEW_nit__parser__ReduceAction47(const struct type* type);
extern const struct type type_nit__parser__ReduceAction47;
val* NEW_nit__parser__ReduceAction48(const struct type* type);
extern const struct type type_nit__parser__ReduceAction48;
val* NEW_nit__parser__ReduceAction49(const struct type* type);
extern const struct type type_nit__parser__ReduceAction49;
val* NEW_nit__parser__ReduceAction50(const struct type* type);
extern const struct type type_nit__parser__ReduceAction50;
val* NEW_nit__parser__ReduceAction51(const struct type* type);
extern const struct type type_nit__parser__ReduceAction51;
val* NEW_nit__parser__ReduceAction52(const struct type* type);
extern const struct type type_nit__parser__ReduceAction52;
val* NEW_nit__parser__ReduceAction53(const struct type* type);
extern const struct type type_nit__parser__ReduceAction53;
val* NEW_nit__parser__ReduceAction54(const struct type* type);
extern const struct type type_nit__parser__ReduceAction54;
val* NEW_nit__parser__ReduceAction55(const struct type* type);
extern const struct type type_nit__parser__ReduceAction55;
val* NEW_nit__parser__ReduceAction56(const struct type* type);
extern const struct type type_nit__parser__ReduceAction56;
val* NEW_nit__parser__ReduceAction57(const struct type* type);
extern const struct type type_nit__parser__ReduceAction57;
val* NEW_nit__parser__ReduceAction58(const struct type* type);
extern const struct type type_nit__parser__ReduceAction58;
val* NEW_nit__parser__ReduceAction59(const struct type* type);
extern const struct type type_nit__parser__ReduceAction59;
val* NEW_nit__parser__ReduceAction60(const struct type* type);
extern const struct type type_nit__parser__ReduceAction60;
val* NEW_nit__parser__ReduceAction61(const struct type* type);
extern const struct type type_nit__parser__ReduceAction61;
val* NEW_nit__parser__ReduceAction62(const struct type* type);
extern const struct type type_nit__parser__ReduceAction62;
val* NEW_nit__parser__ReduceAction63(const struct type* type);
extern const struct type type_nit__parser__ReduceAction63;
val* NEW_nit__parser__ReduceAction64(const struct type* type);
extern const struct type type_nit__parser__ReduceAction64;
val* NEW_nit__parser__ReduceAction65(const struct type* type);
extern const struct type type_nit__parser__ReduceAction65;
val* NEW_nit__parser__ReduceAction66(const struct type* type);
extern const struct type type_nit__parser__ReduceAction66;
val* NEW_nit__parser__ReduceAction67(const struct type* type);
extern const struct type type_nit__parser__ReduceAction67;
val* NEW_nit__parser__ReduceAction68(const struct type* type);
extern const struct type type_nit__parser__ReduceAction68;
val* NEW_nit__parser__ReduceAction69(const struct type* type);
extern const struct type type_nit__parser__ReduceAction69;
val* NEW_nit__parser__ReduceAction70(const struct type* type);
extern const struct type type_nit__parser__ReduceAction70;
val* NEW_nit__parser__ReduceAction71(const struct type* type);
extern const struct type type_nit__parser__ReduceAction71;
val* NEW_nit__parser__ReduceAction72(const struct type* type);
extern const struct type type_nit__parser__ReduceAction72;
val* NEW_nit__parser__ReduceAction74(const struct type* type);
extern const struct type type_nit__parser__ReduceAction74;
val* NEW_nit__parser__ReduceAction75(const struct type* type);
extern const struct type type_nit__parser__ReduceAction75;
val* NEW_nit__parser__ReduceAction78(const struct type* type);
extern const struct type type_nit__parser__ReduceAction78;
val* NEW_nit__parser__ReduceAction79(const struct type* type);
extern const struct type type_nit__parser__ReduceAction79;
val* NEW_nit__parser__ReduceAction80(const struct type* type);
extern const struct type type_nit__parser__ReduceAction80;
val* NEW_nit__parser__ReduceAction81(const struct type* type);
extern const struct type type_nit__parser__ReduceAction81;
val* NEW_nit__parser__ReduceAction82(const struct type* type);
extern const struct type type_nit__parser__ReduceAction82;
val* NEW_nit__parser__ReduceAction83(const struct type* type);
extern const struct type type_nit__parser__ReduceAction83;
val* NEW_nit__parser__ReduceAction84(const struct type* type);
extern const struct type type_nit__parser__ReduceAction84;
val* NEW_nit__parser__ReduceAction85(const struct type* type);
extern const struct type type_nit__parser__ReduceAction85;
val* NEW_nit__parser__ReduceAction86(const struct type* type);
extern const struct type type_nit__parser__ReduceAction86;
val* NEW_nit__parser__ReduceAction87(const struct type* type);
extern const struct type type_nit__parser__ReduceAction87;
val* NEW_nit__parser__ReduceAction88(const struct type* type);
extern const struct type type_nit__parser__ReduceAction88;
val* NEW_nit__parser__ReduceAction89(const struct type* type);
extern const struct type type_nit__parser__ReduceAction89;
val* NEW_nit__parser__ReduceAction90(const struct type* type);
extern const struct type type_nit__parser__ReduceAction90;
val* NEW_nit__parser__ReduceAction91(const struct type* type);
extern const struct type type_nit__parser__ReduceAction91;
val* NEW_nit__parser__ReduceAction92(const struct type* type);
extern const struct type type_nit__parser__ReduceAction92;
val* NEW_nit__parser__ReduceAction93(const struct type* type);
extern const struct type type_nit__parser__ReduceAction93;
val* NEW_nit__parser__ReduceAction94(const struct type* type);
extern const struct type type_nit__parser__ReduceAction94;
val* NEW_nit__parser__ReduceAction95(const struct type* type);
extern const struct type type_nit__parser__ReduceAction95;
val* NEW_nit__parser__ReduceAction96(const struct type* type);
extern const struct type type_nit__parser__ReduceAction96;
val* NEW_nit__parser__ReduceAction97(const struct type* type);
extern const struct type type_nit__parser__ReduceAction97;
val* NEW_nit__parser__ReduceAction98(const struct type* type);
extern const struct type type_nit__parser__ReduceAction98;
val* NEW_nit__parser__ReduceAction99(const struct type* type);
extern const struct type type_nit__parser__ReduceAction99;
val* NEW_nit__parser__ReduceAction100(const struct type* type);
extern const struct type type_nit__parser__ReduceAction100;
val* NEW_nit__parser__ReduceAction101(const struct type* type);
extern const struct type type_nit__parser__ReduceAction101;
val* NEW_nit__parser__ReduceAction102(const struct type* type);
extern const struct type type_nit__parser__ReduceAction102;
val* NEW_nit__parser__ReduceAction103(const struct type* type);
extern const struct type type_nit__parser__ReduceAction103;
val* NEW_nit__parser__ReduceAction104(const struct type* type);
extern const struct type type_nit__parser__ReduceAction104;
val* NEW_nit__parser__ReduceAction105(const struct type* type);
extern const struct type type_nit__parser__ReduceAction105;
val* NEW_nit__parser__ReduceAction106(const struct type* type);
extern const struct type type_nit__parser__ReduceAction106;
val* NEW_nit__parser__ReduceAction107(const struct type* type);
extern const struct type type_nit__parser__ReduceAction107;
val* NEW_nit__parser__ReduceAction108(const struct type* type);
extern const struct type type_nit__parser__ReduceAction108;
val* NEW_nit__parser__ReduceAction109(const struct type* type);
extern const struct type type_nit__parser__ReduceAction109;
val* NEW_nit__parser__ReduceAction110(const struct type* type);
extern const struct type type_nit__parser__ReduceAction110;
val* NEW_nit__parser__ReduceAction111(const struct type* type);
extern const struct type type_nit__parser__ReduceAction111;
val* NEW_nit__parser__ReduceAction112(const struct type* type);
extern const struct type type_nit__parser__ReduceAction112;
val* NEW_nit__parser__ReduceAction114(const struct type* type);
extern const struct type type_nit__parser__ReduceAction114;
val* NEW_nit__parser__ReduceAction115(const struct type* type);
extern const struct type type_nit__parser__ReduceAction115;
val* NEW_nit__parser__ReduceAction116(const struct type* type);
extern const struct type type_nit__parser__ReduceAction116;
val* NEW_nit__parser__ReduceAction117(const struct type* type);
extern const struct type type_nit__parser__ReduceAction117;
val* NEW_nit__parser__ReduceAction118(const struct type* type);
extern const struct type type_nit__parser__ReduceAction118;
val* NEW_nit__parser__ReduceAction119(const struct type* type);
extern const struct type type_nit__parser__ReduceAction119;
val* NEW_nit__parser__ReduceAction120(const struct type* type);
extern const struct type type_nit__parser__ReduceAction120;
val* NEW_nit__parser__ReduceAction121(const struct type* type);
extern const struct type type_nit__parser__ReduceAction121;
val* NEW_nit__parser__ReduceAction123(const struct type* type);
extern const struct type type_nit__parser__ReduceAction123;
val* NEW_nit__parser__ReduceAction124(const struct type* type);
extern const struct type type_nit__parser__ReduceAction124;
val* NEW_nit__parser__ReduceAction126(const struct type* type);
extern const struct type type_nit__parser__ReduceAction126;
val* NEW_nit__parser__ReduceAction127(const struct type* type);
extern const struct type type_nit__parser__ReduceAction127;
val* NEW_nit__parser__ReduceAction128(const struct type* type);
extern const struct type type_nit__parser__ReduceAction128;
val* NEW_nit__parser__ReduceAction129(const struct type* type);
extern const struct type type_nit__parser__ReduceAction129;
val* NEW_nit__parser__ReduceAction130(const struct type* type);
extern const struct type type_nit__parser__ReduceAction130;
val* NEW_nit__parser__ReduceAction131(const struct type* type);
extern const struct type type_nit__parser__ReduceAction131;
val* NEW_nit__parser__ReduceAction132(const struct type* type);
extern const struct type type_nit__parser__ReduceAction132;
val* NEW_nit__parser__ReduceAction133(const struct type* type);
extern const struct type type_nit__parser__ReduceAction133;
val* NEW_nit__parser__ReduceAction134(const struct type* type);
extern const struct type type_nit__parser__ReduceAction134;
val* NEW_nit__parser__ReduceAction135(const struct type* type);
extern const struct type type_nit__parser__ReduceAction135;
val* NEW_nit__parser__ReduceAction137(const struct type* type);
extern const struct type type_nit__parser__ReduceAction137;
val* NEW_nit__parser__ReduceAction138(const struct type* type);
extern const struct type type_nit__parser__ReduceAction138;
val* NEW_nit__parser__ReduceAction139(const struct type* type);
extern const struct type type_nit__parser__ReduceAction139;
val* NEW_nit__parser__ReduceAction140(const struct type* type);
extern const struct type type_nit__parser__ReduceAction140;
val* NEW_nit__parser__ReduceAction141(const struct type* type);
extern const struct type type_nit__parser__ReduceAction141;
val* NEW_nit__parser__ReduceAction143(const struct type* type);
extern const struct type type_nit__parser__ReduceAction143;
val* NEW_nit__parser__ReduceAction144(const struct type* type);
extern const struct type type_nit__parser__ReduceAction144;
val* NEW_nit__parser__ReduceAction145(const struct type* type);
extern const struct type type_nit__parser__ReduceAction145;
val* NEW_nit__parser__ReduceAction146(const struct type* type);
extern const struct type type_nit__parser__ReduceAction146;
val* NEW_nit__parser__ReduceAction147(const struct type* type);
extern const struct type type_nit__parser__ReduceAction147;
val* NEW_nit__parser__ReduceAction148(const struct type* type);
extern const struct type type_nit__parser__ReduceAction148;
val* NEW_nit__parser__ReduceAction149(const struct type* type);
extern const struct type type_nit__parser__ReduceAction149;
val* NEW_nit__parser__ReduceAction150(const struct type* type);
extern const struct type type_nit__parser__ReduceAction150;
val* NEW_nit__parser__ReduceAction154(const struct type* type);
extern const struct type type_nit__parser__ReduceAction154;
val* NEW_nit__parser__ReduceAction155(const struct type* type);
extern const struct type type_nit__parser__ReduceAction155;
val* NEW_nit__parser__ReduceAction156(const struct type* type);
extern const struct type type_nit__parser__ReduceAction156;
val* NEW_nit__parser__ReduceAction157(const struct type* type);
extern const struct type type_nit__parser__ReduceAction157;
val* NEW_nit__parser__ReduceAction158(const struct type* type);
extern const struct type type_nit__parser__ReduceAction158;
val* NEW_nit__parser__ReduceAction159(const struct type* type);
extern const struct type type_nit__parser__ReduceAction159;
val* NEW_nit__parser__ReduceAction160(const struct type* type);
extern const struct type type_nit__parser__ReduceAction160;
val* NEW_nit__parser__ReduceAction161(const struct type* type);
extern const struct type type_nit__parser__ReduceAction161;
val* NEW_nit__parser__ReduceAction162(const struct type* type);
extern const struct type type_nit__parser__ReduceAction162;
val* NEW_nit__parser__ReduceAction163(const struct type* type);
extern const struct type type_nit__parser__ReduceAction163;
val* NEW_nit__parser__ReduceAction167(const struct type* type);
extern const struct type type_nit__parser__ReduceAction167;
val* NEW_nit__parser__ReduceAction168(const struct type* type);
extern const struct type type_nit__parser__ReduceAction168;
val* NEW_nit__parser__ReduceAction169(const struct type* type);
extern const struct type type_nit__parser__ReduceAction169;
val* NEW_nit__parser__ReduceAction170(const struct type* type);
extern const struct type type_nit__parser__ReduceAction170;
val* NEW_nit__parser__ReduceAction171(const struct type* type);
extern const struct type type_nit__parser__ReduceAction171;
val* NEW_nit__parser__ReduceAction172(const struct type* type);
extern const struct type type_nit__parser__ReduceAction172;
val* NEW_nit__parser__ReduceAction173(const struct type* type);
extern const struct type type_nit__parser__ReduceAction173;
val* NEW_nit__parser__ReduceAction181(const struct type* type);
extern const struct type type_nit__parser__ReduceAction181;
val* NEW_nit__parser__ReduceAction182(const struct type* type);
extern const struct type type_nit__parser__ReduceAction182;
val* NEW_nit__parser__ReduceAction183(const struct type* type);
extern const struct type type_nit__parser__ReduceAction183;
val* NEW_nit__parser__ReduceAction185(const struct type* type);
extern const struct type type_nit__parser__ReduceAction185;
val* NEW_nit__parser__ReduceAction186(const struct type* type);
extern const struct type type_nit__parser__ReduceAction186;
val* NEW_nit__parser__ReduceAction187(const struct type* type);
extern const struct type type_nit__parser__ReduceAction187;
val* NEW_nit__parser__ReduceAction189(const struct type* type);
extern const struct type type_nit__parser__ReduceAction189;
val* NEW_nit__parser__ReduceAction190(const struct type* type);
extern const struct type type_nit__parser__ReduceAction190;
val* NEW_nit__parser__ReduceAction191(const struct type* type);
extern const struct type type_nit__parser__ReduceAction191;
val* NEW_nit__parser__ReduceAction192(const struct type* type);
extern const struct type type_nit__parser__ReduceAction192;
val* NEW_nit__parser__ReduceAction193(const struct type* type);
extern const struct type type_nit__parser__ReduceAction193;
val* NEW_nit__parser__ReduceAction195(const struct type* type);
extern const struct type type_nit__parser__ReduceAction195;
val* NEW_nit__parser__ReduceAction196(const struct type* type);
extern const struct type type_nit__parser__ReduceAction196;
val* NEW_nit__parser__ReduceAction198(const struct type* type);
extern const struct type type_nit__parser__ReduceAction198;
val* NEW_nit__parser__ReduceAction199(const struct type* type);
extern const struct type type_nit__parser__ReduceAction199;
val* NEW_nit__parser__ReduceAction200(const struct type* type);
extern const struct type type_nit__parser__ReduceAction200;
val* NEW_nit__parser__ReduceAction201(const struct type* type);
extern const struct type type_nit__parser__ReduceAction201;
val* NEW_nit__parser__ReduceAction202(const struct type* type);
extern const struct type type_nit__parser__ReduceAction202;
val* NEW_nit__parser__ReduceAction203(const struct type* type);
extern const struct type type_nit__parser__ReduceAction203;
val* NEW_nit__parser__ReduceAction204(const struct type* type);
extern const struct type type_nit__parser__ReduceAction204;
val* NEW_nit__parser__ReduceAction205(const struct type* type);
extern const struct type type_nit__parser__ReduceAction205;
val* NEW_nit__parser__ReduceAction206(const struct type* type);
extern const struct type type_nit__parser__ReduceAction206;
val* NEW_nit__parser__ReduceAction207(const struct type* type);
extern const struct type type_nit__parser__ReduceAction207;
val* NEW_nit__parser__ReduceAction208(const struct type* type);
extern const struct type type_nit__parser__ReduceAction208;
val* NEW_nit__parser__ReduceAction209(const struct type* type);
extern const struct type type_nit__parser__ReduceAction209;
val* NEW_nit__parser__ReduceAction210(const struct type* type);
extern const struct type type_nit__parser__ReduceAction210;
val* NEW_nit__parser__ReduceAction211(const struct type* type);
extern const struct type type_nit__parser__ReduceAction211;
val* NEW_nit__parser__ReduceAction212(const struct type* type);
extern const struct type type_nit__parser__ReduceAction212;
val* NEW_nit__parser__ReduceAction215(const struct type* type);
extern const struct type type_nit__parser__ReduceAction215;
val* NEW_nit__parser__ReduceAction216(const struct type* type);
extern const struct type type_nit__parser__ReduceAction216;
val* NEW_nit__parser__ReduceAction217(const struct type* type);
extern const struct type type_nit__parser__ReduceAction217;
val* NEW_nit__parser__ReduceAction218(const struct type* type);
extern const struct type type_nit__parser__ReduceAction218;
val* NEW_nit__parser__ReduceAction219(const struct type* type);
extern const struct type type_nit__parser__ReduceAction219;
val* NEW_nit__parser__ReduceAction220(const struct type* type);
extern const struct type type_nit__parser__ReduceAction220;
val* NEW_nit__parser__ReduceAction223(const struct type* type);
extern const struct type type_nit__parser__ReduceAction223;
val* NEW_nit__parser__ReduceAction224(const struct type* type);
extern const struct type type_nit__parser__ReduceAction224;
val* NEW_nit__parser__ReduceAction225(const struct type* type);
extern const struct type type_nit__parser__ReduceAction225;
val* NEW_nit__parser__ReduceAction226(const struct type* type);
extern const struct type type_nit__parser__ReduceAction226;
val* NEW_nit__parser__ReduceAction227(const struct type* type);
extern const struct type type_nit__parser__ReduceAction227;
val* NEW_nit__parser__ReduceAction228(const struct type* type);
extern const struct type type_nit__parser__ReduceAction228;
val* NEW_nit__parser__ReduceAction229(const struct type* type);
extern const struct type type_nit__parser__ReduceAction229;
val* NEW_nit__parser__ReduceAction230(const struct type* type);
extern const struct type type_nit__parser__ReduceAction230;
val* NEW_nit__parser__ReduceAction231(const struct type* type);
extern const struct type type_nit__parser__ReduceAction231;
val* NEW_nit__parser__ReduceAction234(const struct type* type);
extern const struct type type_nit__parser__ReduceAction234;
val* NEW_nit__parser__ReduceAction235(const struct type* type);
extern const struct type type_nit__parser__ReduceAction235;
val* NEW_nit__parser__ReduceAction236(const struct type* type);
extern const struct type type_nit__parser__ReduceAction236;
val* NEW_nit__parser__ReduceAction237(const struct type* type);
extern const struct type type_nit__parser__ReduceAction237;
val* NEW_nit__parser__ReduceAction238(const struct type* type);
extern const struct type type_nit__parser__ReduceAction238;
val* NEW_nit__parser__ReduceAction239(const struct type* type);
extern const struct type type_nit__parser__ReduceAction239;
val* NEW_nit__parser__ReduceAction242(const struct type* type);
extern const struct type type_nit__parser__ReduceAction242;
val* NEW_nit__parser__ReduceAction243(const struct type* type);
extern const struct type type_nit__parser__ReduceAction243;
val* NEW_nit__parser__ReduceAction244(const struct type* type);
extern const struct type type_nit__parser__ReduceAction244;
val* NEW_nit__parser__ReduceAction245(const struct type* type);
extern const struct type type_nit__parser__ReduceAction245;
val* NEW_nit__parser__ReduceAction246(const struct type* type);
extern const struct type type_nit__parser__ReduceAction246;
val* NEW_nit__parser__ReduceAction247(const struct type* type);
extern const struct type type_nit__parser__ReduceAction247;
val* NEW_nit__parser__ReduceAction248(const struct type* type);
extern const struct type type_nit__parser__ReduceAction248;
val* NEW_nit__parser__ReduceAction249(const struct type* type);
extern const struct type type_nit__parser__ReduceAction249;
val* NEW_nit__parser__ReduceAction250(const struct type* type);
extern const struct type type_nit__parser__ReduceAction250;
val* NEW_nit__parser__ReduceAction251(const struct type* type);
extern const struct type type_nit__parser__ReduceAction251;
val* NEW_nit__parser__ReduceAction252(const struct type* type);
extern const struct type type_nit__parser__ReduceAction252;
val* NEW_nit__parser__ReduceAction253(const struct type* type);
extern const struct type type_nit__parser__ReduceAction253;
val* NEW_nit__parser__ReduceAction254(const struct type* type);
extern const struct type type_nit__parser__ReduceAction254;
val* NEW_nit__parser__ReduceAction255(const struct type* type);
extern const struct type type_nit__parser__ReduceAction255;
val* NEW_nit__parser__ReduceAction256(const struct type* type);
extern const struct type type_nit__parser__ReduceAction256;
val* NEW_nit__parser__ReduceAction257(const struct type* type);
extern const struct type type_nit__parser__ReduceAction257;
val* NEW_nit__parser__ReduceAction258(const struct type* type);
extern const struct type type_nit__parser__ReduceAction258;
val* NEW_nit__parser__ReduceAction259(const struct type* type);
extern const struct type type_nit__parser__ReduceAction259;
val* NEW_nit__parser__ReduceAction260(const struct type* type);
extern const struct type type_nit__parser__ReduceAction260;
val* NEW_nit__parser__ReduceAction263(const struct type* type);
extern const struct type type_nit__parser__ReduceAction263;
val* NEW_nit__parser__ReduceAction264(const struct type* type);
extern const struct type type_nit__parser__ReduceAction264;
val* NEW_nit__parser__ReduceAction265(const struct type* type);
extern const struct type type_nit__parser__ReduceAction265;
val* NEW_nit__parser__ReduceAction266(const struct type* type);
extern const struct type type_nit__parser__ReduceAction266;
val* NEW_nit__parser__ReduceAction267(const struct type* type);
extern const struct type type_nit__parser__ReduceAction267;
val* NEW_nit__parser__ReduceAction268(const struct type* type);
extern const struct type type_nit__parser__ReduceAction268;
val* NEW_nit__parser__ReduceAction269(const struct type* type);
extern const struct type type_nit__parser__ReduceAction269;
val* NEW_nit__parser__ReduceAction270(const struct type* type);
extern const struct type type_nit__parser__ReduceAction270;
val* NEW_nit__parser__ReduceAction271(const struct type* type);
extern const struct type type_nit__parser__ReduceAction271;
val* NEW_nit__parser__ReduceAction272(const struct type* type);
extern const struct type type_nit__parser__ReduceAction272;
val* NEW_nit__parser__ReduceAction274(const struct type* type);
extern const struct type type_nit__parser__ReduceAction274;
val* NEW_nit__parser__ReduceAction275(const struct type* type);
extern const struct type type_nit__parser__ReduceAction275;
val* NEW_nit__parser__ReduceAction276(const struct type* type);
extern const struct type type_nit__parser__ReduceAction276;
val* NEW_nit__parser__ReduceAction277(const struct type* type);
extern const struct type type_nit__parser__ReduceAction277;
val* NEW_nit__parser__ReduceAction278(const struct type* type);
extern const struct type type_nit__parser__ReduceAction278;
val* NEW_nit__parser__ReduceAction280(const struct type* type);
extern const struct type type_nit__parser__ReduceAction280;
val* NEW_nit__parser__ReduceAction282(const struct type* type);
extern const struct type type_nit__parser__ReduceAction282;
val* NEW_nit__parser__ReduceAction283(const struct type* type);
extern const struct type type_nit__parser__ReduceAction283;
val* NEW_nit__parser__ReduceAction284(const struct type* type);
extern const struct type type_nit__parser__ReduceAction284;
val* NEW_nit__parser__ReduceAction285(const struct type* type);
extern const struct type type_nit__parser__ReduceAction285;
val* NEW_nit__parser__ReduceAction287(const struct type* type);
extern const struct type type_nit__parser__ReduceAction287;
val* NEW_nit__parser__ReduceAction289(const struct type* type);
extern const struct type type_nit__parser__ReduceAction289;
val* NEW_nit__parser__ReduceAction290(const struct type* type);
extern const struct type type_nit__parser__ReduceAction290;
val* NEW_nit__parser__ReduceAction291(const struct type* type);
extern const struct type type_nit__parser__ReduceAction291;
val* NEW_nit__parser__ReduceAction292(const struct type* type);
extern const struct type type_nit__parser__ReduceAction292;
val* NEW_nit__parser__ReduceAction293(const struct type* type);
extern const struct type type_nit__parser__ReduceAction293;
val* NEW_nit__parser__ReduceAction294(const struct type* type);
extern const struct type type_nit__parser__ReduceAction294;
val* NEW_nit__parser__ReduceAction295(const struct type* type);
extern const struct type type_nit__parser__ReduceAction295;
val* NEW_nit__parser__ReduceAction296(const struct type* type);
extern const struct type type_nit__parser__ReduceAction296;
val* NEW_nit__parser__ReduceAction298(const struct type* type);
extern const struct type type_nit__parser__ReduceAction298;
val* NEW_nit__parser__ReduceAction300(const struct type* type);
extern const struct type type_nit__parser__ReduceAction300;
val* NEW_nit__parser__ReduceAction302(const struct type* type);
extern const struct type type_nit__parser__ReduceAction302;
val* NEW_nit__parser__ReduceAction304(const struct type* type);
extern const struct type type_nit__parser__ReduceAction304;
val* NEW_nit__parser__ReduceAction305(const struct type* type);
extern const struct type type_nit__parser__ReduceAction305;
val* NEW_nit__parser__ReduceAction307(const struct type* type);
extern const struct type type_nit__parser__ReduceAction307;
val* NEW_nit__parser__ReduceAction308(const struct type* type);
extern const struct type type_nit__parser__ReduceAction308;
val* NEW_nit__parser__ReduceAction310(const struct type* type);
extern const struct type type_nit__parser__ReduceAction310;
val* NEW_nit__parser__ReduceAction311(const struct type* type);
extern const struct type type_nit__parser__ReduceAction311;
val* NEW_nit__parser__ReduceAction312(const struct type* type);
extern const struct type type_nit__parser__ReduceAction312;
val* NEW_nit__parser__ReduceAction314(const struct type* type);
extern const struct type type_nit__parser__ReduceAction314;
val* NEW_nit__parser__ReduceAction316(const struct type* type);
extern const struct type type_nit__parser__ReduceAction316;
val* NEW_nit__parser__ReduceAction317(const struct type* type);
extern const struct type type_nit__parser__ReduceAction317;
val* NEW_nit__parser__ReduceAction318(const struct type* type);
extern const struct type type_nit__parser__ReduceAction318;
val* NEW_nit__parser__ReduceAction319(const struct type* type);
extern const struct type type_nit__parser__ReduceAction319;
val* NEW_nit__parser__ReduceAction321(const struct type* type);
extern const struct type type_nit__parser__ReduceAction321;
val* NEW_nit__parser__ReduceAction322(const struct type* type);
extern const struct type type_nit__parser__ReduceAction322;
val* NEW_nit__parser__ReduceAction323(const struct type* type);
extern const struct type type_nit__parser__ReduceAction323;
val* NEW_nit__parser__ReduceAction324(const struct type* type);
extern const struct type type_nit__parser__ReduceAction324;
val* NEW_nit__parser__ReduceAction326(const struct type* type);
extern const struct type type_nit__parser__ReduceAction326;
val* NEW_nit__parser__ReduceAction327(const struct type* type);
extern const struct type type_nit__parser__ReduceAction327;
val* NEW_nit__parser__ReduceAction329(const struct type* type);
extern const struct type type_nit__parser__ReduceAction329;
val* NEW_nit__parser__ReduceAction331(const struct type* type);
extern const struct type type_nit__parser__ReduceAction331;
val* NEW_nit__parser__ReduceAction333(const struct type* type);
extern const struct type type_nit__parser__ReduceAction333;
val* NEW_nit__parser__ReduceAction337(const struct type* type);
extern const struct type type_nit__parser__ReduceAction337;
val* NEW_nit__parser__ReduceAction339(const struct type* type);
extern const struct type type_nit__parser__ReduceAction339;
val* NEW_nit__parser__ReduceAction341(const struct type* type);
extern const struct type type_nit__parser__ReduceAction341;
val* NEW_nit__parser__ReduceAction345(const struct type* type);
extern const struct type type_nit__parser__ReduceAction345;
val* NEW_nit__parser__ReduceAction347(const struct type* type);
extern const struct type type_nit__parser__ReduceAction347;
val* NEW_nit__parser__ReduceAction349(const struct type* type);
extern const struct type type_nit__parser__ReduceAction349;
val* NEW_nit__parser__ReduceAction350(const struct type* type);
extern const struct type type_nit__parser__ReduceAction350;
val* NEW_nit__parser__ReduceAction351(const struct type* type);
extern const struct type type_nit__parser__ReduceAction351;
val* NEW_nit__parser__ReduceAction352(const struct type* type);
extern const struct type type_nit__parser__ReduceAction352;
val* NEW_nit__parser__ReduceAction353(const struct type* type);
extern const struct type type_nit__parser__ReduceAction353;
val* NEW_nit__parser__ReduceAction354(const struct type* type);
extern const struct type type_nit__parser__ReduceAction354;
val* NEW_nit__parser__ReduceAction355(const struct type* type);
extern const struct type type_nit__parser__ReduceAction355;
val* NEW_nit__parser__ReduceAction356(const struct type* type);
extern const struct type type_nit__parser__ReduceAction356;
val* NEW_nit__parser__ReduceAction359(const struct type* type);
extern const struct type type_nit__parser__ReduceAction359;
val* NEW_nit__parser__ReduceAction360(const struct type* type);
extern const struct type type_nit__parser__ReduceAction360;
val* NEW_nit__parser__ReduceAction361(const struct type* type);
extern const struct type type_nit__parser__ReduceAction361;
val* NEW_nit__parser__ReduceAction363(const struct type* type);
extern const struct type type_nit__parser__ReduceAction363;
val* NEW_nit__parser__ReduceAction364(const struct type* type);
extern const struct type type_nit__parser__ReduceAction364;
val* NEW_nit__parser__ReduceAction365(const struct type* type);
extern const struct type type_nit__parser__ReduceAction365;
val* NEW_nit__parser__ReduceAction366(const struct type* type);
extern const struct type type_nit__parser__ReduceAction366;
val* NEW_nit__parser__ReduceAction367(const struct type* type);
extern const struct type type_nit__parser__ReduceAction367;
val* NEW_nit__parser__ReduceAction368(const struct type* type);
extern const struct type type_nit__parser__ReduceAction368;
val* NEW_nit__parser__ReduceAction369(const struct type* type);
extern const struct type type_nit__parser__ReduceAction369;
val* NEW_nit__parser__ReduceAction370(const struct type* type);
extern const struct type type_nit__parser__ReduceAction370;
val* NEW_nit__parser__ReduceAction371(const struct type* type);
extern const struct type type_nit__parser__ReduceAction371;
val* NEW_nit__parser__ReduceAction372(const struct type* type);
extern const struct type type_nit__parser__ReduceAction372;
val* NEW_nit__parser__ReduceAction373(const struct type* type);
extern const struct type type_nit__parser__ReduceAction373;
val* NEW_nit__parser__ReduceAction376(const struct type* type);
extern const struct type type_nit__parser__ReduceAction376;
val* NEW_nit__parser__ReduceAction377(const struct type* type);
extern const struct type type_nit__parser__ReduceAction377;
val* NEW_nit__parser__ReduceAction378(const struct type* type);
extern const struct type type_nit__parser__ReduceAction378;
val* NEW_nit__parser__ReduceAction379(const struct type* type);
extern const struct type type_nit__parser__ReduceAction379;
val* NEW_nit__parser__ReduceAction381(const struct type* type);
extern const struct type type_nit__parser__ReduceAction381;
val* NEW_nit__parser__ReduceAction382(const struct type* type);
extern const struct type type_nit__parser__ReduceAction382;
val* NEW_nit__parser__ReduceAction383(const struct type* type);
extern const struct type type_nit__parser__ReduceAction383;
val* NEW_nit__parser__ReduceAction384(const struct type* type);
extern const struct type type_nit__parser__ReduceAction384;
val* NEW_nit__parser__ReduceAction386(const struct type* type);
extern const struct type type_nit__parser__ReduceAction386;
val* NEW_nit__parser__ReduceAction388(const struct type* type);
extern const struct type type_nit__parser__ReduceAction388;
val* NEW_nit__parser__ReduceAction389(const struct type* type);
extern const struct type type_nit__parser__ReduceAction389;
val* NEW_nit__parser__ReduceAction390(const struct type* type);
extern const struct type type_nit__parser__ReduceAction390;
val* NEW_nit__parser__ReduceAction391(const struct type* type);
extern const struct type type_nit__parser__ReduceAction391;
val* NEW_nit__parser__ReduceAction392(const struct type* type);
extern const struct type type_nit__parser__ReduceAction392;
val* NEW_nit__parser__ReduceAction393(const struct type* type);
extern const struct type type_nit__parser__ReduceAction393;
val* NEW_nit__parser__ReduceAction396(const struct type* type);
extern const struct type type_nit__parser__ReduceAction396;
val* NEW_nit__parser__ReduceAction397(const struct type* type);
extern const struct type type_nit__parser__ReduceAction397;
val* NEW_nit__parser__ReduceAction398(const struct type* type);
extern const struct type type_nit__parser__ReduceAction398;
val* NEW_nit__parser__ReduceAction399(const struct type* type);
extern const struct type type_nit__parser__ReduceAction399;
val* NEW_nit__parser__ReduceAction400(const struct type* type);
extern const struct type type_nit__parser__ReduceAction400;
val* NEW_nit__parser__ReduceAction402(const struct type* type);
extern const struct type type_nit__parser__ReduceAction402;
val* NEW_nit__parser__ReduceAction403(const struct type* type);
extern const struct type type_nit__parser__ReduceAction403;
val* NEW_nit__parser__ReduceAction404(const struct type* type);
extern const struct type type_nit__parser__ReduceAction404;
val* NEW_nit__parser__ReduceAction405(const struct type* type);
extern const struct type type_nit__parser__ReduceAction405;
val* NEW_nit__parser__ReduceAction406(const struct type* type);
extern const struct type type_nit__parser__ReduceAction406;
val* NEW_nit__parser__ReduceAction409(const struct type* type);
extern const struct type type_nit__parser__ReduceAction409;
val* NEW_nit__parser__ReduceAction411(const struct type* type);
extern const struct type type_nit__parser__ReduceAction411;
val* NEW_nit__parser__ReduceAction413(const struct type* type);
extern const struct type type_nit__parser__ReduceAction413;
val* NEW_nit__parser__ReduceAction414(const struct type* type);
extern const struct type type_nit__parser__ReduceAction414;
val* NEW_nit__parser__ReduceAction415(const struct type* type);
extern const struct type type_nit__parser__ReduceAction415;
val* NEW_nit__parser__ReduceAction416(const struct type* type);
extern const struct type type_nit__parser__ReduceAction416;
val* NEW_nit__parser__ReduceAction417(const struct type* type);
extern const struct type type_nit__parser__ReduceAction417;
val* NEW_nit__parser__ReduceAction418(const struct type* type);
extern const struct type type_nit__parser__ReduceAction418;
val* NEW_nit__parser__ReduceAction419(const struct type* type);
extern const struct type type_nit__parser__ReduceAction419;
val* NEW_nit__parser__ReduceAction420(const struct type* type);
extern const struct type type_nit__parser__ReduceAction420;
val* NEW_nit__parser__ReduceAction421(const struct type* type);
extern const struct type type_nit__parser__ReduceAction421;
val* NEW_nit__parser__ReduceAction422(const struct type* type);
extern const struct type type_nit__parser__ReduceAction422;
val* NEW_nit__parser__ReduceAction426(const struct type* type);
extern const struct type type_nit__parser__ReduceAction426;
val* NEW_nit__parser__ReduceAction429(const struct type* type);
extern const struct type type_nit__parser__ReduceAction429;
val* NEW_nit__parser__ReduceAction430(const struct type* type);
extern const struct type type_nit__parser__ReduceAction430;
val* NEW_nit__parser__ReduceAction431(const struct type* type);
extern const struct type type_nit__parser__ReduceAction431;
val* NEW_nit__parser__ReduceAction432(const struct type* type);
extern const struct type type_nit__parser__ReduceAction432;
val* NEW_nit__parser__ReduceAction433(const struct type* type);
extern const struct type type_nit__parser__ReduceAction433;
val* NEW_nit__parser__ReduceAction434(const struct type* type);
extern const struct type type_nit__parser__ReduceAction434;
val* NEW_nit__parser__ReduceAction435(const struct type* type);
extern const struct type type_nit__parser__ReduceAction435;
val* NEW_nit__parser__ReduceAction436(const struct type* type);
extern const struct type type_nit__parser__ReduceAction436;
val* NEW_nit__parser__ReduceAction438(const struct type* type);
extern const struct type type_nit__parser__ReduceAction438;
val* NEW_nit__parser__ReduceAction440(const struct type* type);
extern const struct type type_nit__parser__ReduceAction440;
val* NEW_nit__parser__ReduceAction441(const struct type* type);
extern const struct type type_nit__parser__ReduceAction441;
val* NEW_nit__parser__ReduceAction443(const struct type* type);
extern const struct type type_nit__parser__ReduceAction443;
val* NEW_nit__parser__ReduceAction444(const struct type* type);
extern const struct type type_nit__parser__ReduceAction444;
val* NEW_nit__parser__ReduceAction445(const struct type* type);
extern const struct type type_nit__parser__ReduceAction445;
val* NEW_nit__parser__ReduceAction446(const struct type* type);
extern const struct type type_nit__parser__ReduceAction446;
val* NEW_nit__parser__ReduceAction447(const struct type* type);
extern const struct type type_nit__parser__ReduceAction447;
val* NEW_nit__parser__ReduceAction448(const struct type* type);
extern const struct type type_nit__parser__ReduceAction448;
val* NEW_nit__parser__ReduceAction449(const struct type* type);
extern const struct type type_nit__parser__ReduceAction449;
val* NEW_nit__parser__ReduceAction450(const struct type* type);
extern const struct type type_nit__parser__ReduceAction450;
val* NEW_nit__parser__ReduceAction451(const struct type* type);
extern const struct type type_nit__parser__ReduceAction451;
val* NEW_nit__parser__ReduceAction452(const struct type* type);
extern const struct type type_nit__parser__ReduceAction452;
val* NEW_nit__parser__ReduceAction453(const struct type* type);
extern const struct type type_nit__parser__ReduceAction453;
val* NEW_nit__parser__ReduceAction454(const struct type* type);
extern const struct type type_nit__parser__ReduceAction454;
val* NEW_nit__parser__ReduceAction455(const struct type* type);
extern const struct type type_nit__parser__ReduceAction455;
val* NEW_nit__parser__ReduceAction457(const struct type* type);
extern const struct type type_nit__parser__ReduceAction457;
val* NEW_nit__parser__ReduceAction458(const struct type* type);
extern const struct type type_nit__parser__ReduceAction458;
val* NEW_nit__parser__ReduceAction459(const struct type* type);
extern const struct type type_nit__parser__ReduceAction459;
val* NEW_nit__parser__ReduceAction461(const struct type* type);
extern const struct type type_nit__parser__ReduceAction461;
val* NEW_nit__parser__ReduceAction462(const struct type* type);
extern const struct type type_nit__parser__ReduceAction462;
val* NEW_nit__parser__ReduceAction463(const struct type* type);
extern const struct type type_nit__parser__ReduceAction463;
val* NEW_nit__parser__ReduceAction465(const struct type* type);
extern const struct type type_nit__parser__ReduceAction465;
val* NEW_nit__parser__ReduceAction466(const struct type* type);
extern const struct type type_nit__parser__ReduceAction466;
val* NEW_nit__parser__ReduceAction468(const struct type* type);
extern const struct type type_nit__parser__ReduceAction468;
val* NEW_nit__parser__ReduceAction469(const struct type* type);
extern const struct type type_nit__parser__ReduceAction469;
val* NEW_nit__parser__ReduceAction471(const struct type* type);
extern const struct type type_nit__parser__ReduceAction471;
val* NEW_nit__parser__ReduceAction472(const struct type* type);
extern const struct type type_nit__parser__ReduceAction472;
val* NEW_nit__parser__ReduceAction475(const struct type* type);
extern const struct type type_nit__parser__ReduceAction475;
val* NEW_nit__parser__ReduceAction476(const struct type* type);
extern const struct type type_nit__parser__ReduceAction476;
val* NEW_nit__parser__ReduceAction477(const struct type* type);
extern const struct type type_nit__parser__ReduceAction477;
val* NEW_nit__parser__ReduceAction841(const struct type* type);
extern const struct type type_nit__parser__ReduceAction841;
val* NEW_nit__parser__ReduceAction843(const struct type* type);
extern const struct type type_nit__parser__ReduceAction843;
val* NEW_nit__parser__ReduceAction844(const struct type* type);
extern const struct type type_nit__parser__ReduceAction844;
val* NEW_nit__parser__ReduceAction845(const struct type* type);
extern const struct type type_nit__parser__ReduceAction845;
val* NEW_nit__parser__ReduceAction846(const struct type* type);
extern const struct type type_nit__parser__ReduceAction846;
val* NEW_nit__parser__ReduceAction847(const struct type* type);
extern const struct type type_nit__parser__ReduceAction847;
val* NEW_nit__parser__ReduceAction854(const struct type* type);
extern const struct type type_nit__parser__ReduceAction854;
val* NEW_nit__parser__ReduceAction855(const struct type* type);
extern const struct type type_nit__parser__ReduceAction855;
val* NEW_nit__parser__ReduceAction880(const struct type* type);
extern const struct type type_nit__parser__ReduceAction880;
val* NEW_nit__parser__ReduceAction881(const struct type* type);
extern const struct type type_nit__parser__ReduceAction881;
val* NEW_nit__parser__ReduceAction1039(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1039;
val* NEW_nit__parser__ReduceAction1040(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1040;
val* NEW_nit__parser__ReduceAction1041(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1041;
val* NEW_nit__parser__ReduceAction1042(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1042;
val* NEW_nit__parser__ReduceAction1043(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1043;
val* NEW_nit__parser__ReduceAction1044(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1044;
val* NEW_nit__parser__ReduceAction1045(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1045;
val* NEW_nit__parser__ReduceAction1046(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1046;
val* NEW_nit__parser__ReduceAction1048(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1048;
val* NEW_nit__parser__ReduceAction1049(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1049;
val* NEW_nit__parser__ReduceAction1050(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1050;
val* NEW_nit__parser__ReduceAction1051(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1051;
val* NEW_nit__parser__ReduceAction1052(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1052;
val* NEW_nit__parser__ReduceAction1054(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1054;
val* NEW_nit__parser__ReduceAction1056(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1056;
val* NEW_nit__parser__ReduceAction1062(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1062;
val* NEW_nit__parser__ReduceAction1064(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1064;
val* NEW_nit__parser__ReduceAction1072(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1072;
val* NEW_nit__parser__ReduceAction1073(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1073;
val* NEW_nit__parser__ReduceAction1074(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1074;
val* NEW_nit__parser__ReduceAction1075(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1075;
val* NEW_nit__parser__ReduceAction1076(const struct type* type);
extern const struct type type_nit__parser__ReduceAction1076;
extern const int COLOR_standard__Array__standard__Array___35dE;
val* NEW_standard__NativeArray(int length, const struct type* type);
extern const int COLOR_standard__NativeArray__standard__Array___35dE;
extern const int COLOR_standard__array__Array__with_native;
extern const int COLOR_standard__array__Array__with_items;
extern const int COLOR_nit__parser_work__Parser___reduce_table;
extern const int COLOR_nit__parser_work__Parser__pop;
extern const struct type type_standard__Array__standard__Object;
extern const struct type type_nullable__nit__AClassdef;
extern const char FILE_nit__parser[];
extern const int COLOR_standard__kernel__Object___33d_61d;
extern const int COLOR_standard__abstract_collection__SimpleCollection__add;
val* NEW_nit__AModule(const struct type* type);
extern const struct type type_nit__AModule;
extern const int COLOR_nit__parser_prod__AModule__init_amodule;
extern const int COLOR_nit__parser_work__ReduceAction___goto;
extern const int COLOR_nit__parser_work__Parser__go_to;
extern const int COLOR_nit__parser_work__Parser__push;
extern const struct type type_nullable__nit__AModuledecl;
extern const int COLOR_nit__parser_work__ReduceAction__concat;
extern const struct type type_nullable__nit__ADoc;
extern const struct type type_nullable__nit__TKwredef;
extern const struct type type_nullable__nit__AVisibility;
extern const struct type type_nullable__nit__TKwmodule;
extern const struct type type_nullable__nit__AModuleName;
extern const struct type type_nullable__nit__AAnnotations;
val* NEW_nit__AModuledecl(const struct type* type);
extern const struct type type_nit__AModuledecl;
extern const int COLOR_nit__parser_prod__AModuledecl__init_amoduledecl;
extern const struct type type_nullable__nit__TKwimport;
val* NEW_nit__AStdImport(const struct type* type);
extern const struct type type_nit__AStdImport;
extern const int COLOR_nit__parser_prod__AStdImport__init_astdimport;
extern const struct type type_nullable__nit__TKwend;
val* NEW_nit__ANoImport(const struct type* type);
extern const struct type type_nit__ANoImport;
extern const int COLOR_nit__parser_prod__ANoImport__init_anoimport;
extern const struct type type_nullable__nit__APropdef;
val* NEW_nit__ATopClassdef(const struct type* type);
extern const struct type type_nit__ATopClassdef;
extern const int COLOR_nit__parser_prod__ATopClassdef__init_atopclassdef;
val* NEW_nit__AMainClassdef(const struct type* type);
extern const struct type type_nit__AMainClassdef;
extern const int COLOR_nit__parser_prod__AMainClassdef__init_amainclassdef;
extern const struct type type_nullable__nit__AExpr;
val* NEW_nit__AMainMethPropdef(const struct type* type);
extern const struct type type_nit__AMainMethPropdef;
extern const int COLOR_nit__parser_prod__AMainMethPropdef__init_amainmethpropdef;
extern const struct type type_nullable__nit__AClasskind;
extern const struct type type_nullable__nit__TClassid;
val* NEW_nit__AStdClassdef(const struct type* type);
extern const struct type type_nit__AStdClassdef;
extern const int COLOR_nit__parser_prod__AStdClassdef__init_astdclassdef;
extern const struct type type_nullable__nit__AExternCodeBlock;
extern const struct type type_nullable__nit__TKwclass;
val* NEW_nit__AConcreteClasskind(const struct type* type);
extern const struct type type_nit__AConcreteClasskind;
extern const int COLOR_nit__parser_prod__AConcreteClasskind__init_aconcreteclasskind;
extern const struct type type_nullable__nit__TKwabstract;
val* NEW_nit__AAbstractClasskind(const struct type* type);
extern const struct type type_nit__AAbstractClasskind;
extern const int COLOR_nit__parser_prod__AAbstractClasskind__init_aabstractclasskind;
extern const struct type type_nullable__nit__TKwinterface;
val* NEW_nit__AInterfaceClasskind(const struct type* type);
extern const struct type type_nit__AInterfaceClasskind;
extern const int COLOR_nit__parser_prod__AInterfaceClasskind__init_ainterfaceclasskind;
extern const struct type type_nullable__nit__TKwenum;
val* NEW_nit__AEnumClasskind(const struct type* type);
extern const struct type type_nit__AEnumClasskind;
extern const int COLOR_nit__parser_prod__AEnumClasskind__init_aenumclasskind;
extern const struct type type_nullable__nit__TKwextern;
val* NEW_nit__AExternClasskind(const struct type* type);
extern const struct type type_nit__AExternClasskind;
extern const int COLOR_nit__parser_prod__AExternClasskind__init_aexternclasskind;
extern const struct type type_nullable__nit__AType;
val* NEW_nit__AFormaldef(const struct type* type);
extern const struct type type_nit__AFormaldef;
extern const int COLOR_nit__parser_prod__AFormaldef__init_aformaldef;
extern const struct type type_nullable__nit__TKwsuper;
val* NEW_nit__ASuperPropdef(const struct type* type);
extern const struct type type_nit__ASuperPropdef;
extern const int COLOR_nit__parser_prod__ASuperPropdef__init_asuperpropdef;
extern const struct type type_nullable__nit__TKwmeth;
extern const struct type type_nullable__nit__AMethid;
extern const struct type type_nullable__nit__ASignature;
val* NEW_nit__AMethPropdef(const struct type* type);
extern const struct type type_nit__AMethPropdef;
extern const int COLOR_nit__parser_prod__AMethPropdef__init_amethpropdef;
extern const struct type type_nullable__nit__TKwnew;
extern const struct type type_nullable__nit__AExternCalls;
extern const struct type type_nullable__nit__TKwvar;
extern const struct type type_nullable__nit__TId;
val* NEW_nit__AAttrPropdef(const struct type* type);
extern const struct type type_nit__AAttrPropdef;
extern const int COLOR_nit__parser_prod__AAttrPropdef__init_aattrpropdef;
extern const struct type type_nullable__nit__TKwinit;
extern const struct type type_nullable__nit__TKwtype;
val* NEW_nit__ATypePropdef(const struct type* type);
extern const struct type type_nit__ATypePropdef;
extern const int COLOR_nit__parser_prod__ATypePropdef__init_atypepropdef;
val* NEW_nit__APublicVisibility(const struct type* type);
extern const struct type type_nit__APublicVisibility;
extern const int COLOR_nit__parser_prod__APublicVisibility__init_apublicvisibility;
extern const struct type type_nullable__nit__TKwpublic;
extern const struct type type_nullable__nit__TKwprivate;
val* NEW_nit__APrivateVisibility(const struct type* type);
extern const struct type type_nit__APrivateVisibility;
extern const int COLOR_nit__parser_prod__APrivateVisibility__init_aprivatevisibility;
extern const struct type type_nullable__nit__TKwprotected;
val* NEW_nit__AProtectedVisibility(const struct type* type);
extern const struct type type_nit__AProtectedVisibility;
extern const int COLOR_nit__parser_prod__AProtectedVisibility__init_aprotectedvisibility;
extern const struct type type_nullable__nit__TKwintrude;
val* NEW_nit__AIntrudeVisibility(const struct type* type);
extern const struct type type_nit__AIntrudeVisibility;
extern const int COLOR_nit__parser_prod__AIntrudeVisibility__init_aintrudevisibility;
extern const struct type type_nullable__nit__TPlus;
val* NEW_nit__APlusMethid(const struct type* type);
extern const struct type type_nit__APlusMethid;
extern const int COLOR_nit__parser_prod__APlusMethid__init_aplusmethid;
extern const struct type type_nullable__nit__TMinus;
val* NEW_nit__AMinusMethid(const struct type* type);
extern const struct type type_nit__AMinusMethid;
extern const int COLOR_nit__parser_prod__AMinusMethid__init_aminusmethid;
extern const struct type type_nullable__nit__TStar;
val* NEW_nit__AStarMethid(const struct type* type);
extern const struct type type_nit__AStarMethid;
extern const int COLOR_nit__parser_prod__AStarMethid__init_astarmethid;
extern const struct type type_nullable__nit__TStarstar;
val* NEW_nit__AStarstarMethid(const struct type* type);
extern const struct type type_nit__AStarstarMethid;
extern const int COLOR_nit__parser_prod__AStarstarMethid__init_astarstarmethid;
extern const struct type type_nullable__nit__TSlash;
val* NEW_nit__ASlashMethid(const struct type* type);
extern const struct type type_nit__ASlashMethid;
extern const int COLOR_nit__parser_prod__ASlashMethid__init_aslashmethid;
extern const struct type type_nullable__nit__TPercent;
val* NEW_nit__APercentMethid(const struct type* type);
extern const struct type type_nit__APercentMethid;
extern const int COLOR_nit__parser_prod__APercentMethid__init_apercentmethid;
extern const struct type type_nullable__nit__TPipe;
val* NEW_nit__APipeMethid(const struct type* type);
extern const struct type type_nit__APipeMethid;
extern const int COLOR_nit__parser_prod__APipeMethid__init_apipemethid;
extern const struct type type_nullable__nit__TCaret;
val* NEW_nit__ACaretMethid(const struct type* type);
extern const struct type type_nit__ACaretMethid;
extern const int COLOR_nit__parser_prod__ACaretMethid__init_acaretmethid;
extern const struct type type_nullable__nit__TAmp;
val* NEW_nit__AAmpMethid(const struct type* type);
extern const struct type type_nit__AAmpMethid;
extern const int COLOR_nit__parser_prod__AAmpMethid__init_aampmethid;
extern const struct type type_nullable__nit__TTilde;
val* NEW_nit__ATildeMethid(const struct type* type);
extern const struct type type_nit__ATildeMethid;
extern const int COLOR_nit__parser_prod__ATildeMethid__init_atildemethid;
extern const struct type type_nullable__nit__TEq;
val* NEW_nit__AEqMethid(const struct type* type);
extern const struct type type_nit__AEqMethid;
extern const int COLOR_nit__parser_prod__AEqMethid__init_aeqmethid;
extern const struct type type_nullable__nit__TNe;
val* NEW_nit__ANeMethid(const struct type* type);
extern const struct type type_nit__ANeMethid;
extern const int COLOR_nit__parser_prod__ANeMethid__init_anemethid;
extern const struct type type_nullable__nit__TLe;
val* NEW_nit__ALeMethid(const struct type* type);
extern const struct type type_nit__ALeMethid;
extern const int COLOR_nit__parser_prod__ALeMethid__init_alemethid;
extern const struct type type_nullable__nit__TGe;
val* NEW_nit__AGeMethid(const struct type* type);
extern const struct type type_nit__AGeMethid;
extern const int COLOR_nit__parser_prod__AGeMethid__init_agemethid;
extern const struct type type_nullable__nit__TLt;
val* NEW_nit__ALtMethid(const struct type* type);
extern const struct type type_nit__ALtMethid;
extern const int COLOR_nit__parser_prod__ALtMethid__init_altmethid;
extern const struct type type_nullable__nit__TGt;
val* NEW_nit__AGtMethid(const struct type* type);
extern const struct type type_nit__AGtMethid;
extern const int COLOR_nit__parser_prod__AGtMethid__init_agtmethid;
extern const struct type type_nullable__nit__TLl;
val* NEW_nit__ALlMethid(const struct type* type);
extern const struct type type_nit__ALlMethid;
extern const int COLOR_nit__parser_prod__ALlMethid__init_allmethid;
extern const struct type type_nullable__nit__TGg;
val* NEW_nit__AGgMethid(const struct type* type);
extern const struct type type_nit__AGgMethid;
extern const int COLOR_nit__parser_prod__AGgMethid__init_aggmethid;
extern const struct type type_nullable__nit__TObra;
extern const struct type type_nullable__nit__TCbra;
val* NEW_nit__ABraMethid(const struct type* type);
extern const struct type type_nit__ABraMethid;
extern const int COLOR_nit__parser_prod__ABraMethid__init_abramethid;
extern const struct type type_nullable__nit__TStarship;
val* NEW_nit__AStarshipMethid(const struct type* type);
extern const struct type type_nit__AStarshipMethid;
extern const int COLOR_nit__parser_prod__AStarshipMethid__init_astarshipmethid;
extern const struct type type_nullable__nit__TAssign;
val* NEW_nit__AAssignMethid(const struct type* type);
extern const struct type type_nit__AAssignMethid;
extern const int COLOR_nit__parser_prod__AAssignMethid__init_aassignmethid;
val* NEW_nit__ABraassignMethid(const struct type* type);
extern const struct type type_nit__ABraassignMethid;
extern const int COLOR_nit__parser_prod__ABraassignMethid__init_abraassignmethid;
val* NEW_nit__AIdMethid(const struct type* type);
extern const struct type type_nit__AIdMethid;
extern const int COLOR_nit__parser_prod__AIdMethid__init_aidmethid;
extern const struct type type_nullable__nit__TOpar;
extern const struct type type_nullable__nit__TCpar;
val* NEW_nit__ASignature(const struct type* type);
extern const struct type type_nit__ASignature;
extern const int COLOR_nit__parser_prod__ASignature__init_asignature;
val* NEW_nit__AParam(const struct type* type);
extern const struct type type_nit__AParam;
extern const int COLOR_nit__parser_prod__AParam__init_aparam;
extern const struct type type_nullable__nit__TDotdotdot;
extern const struct type type_nullable__nit__AExternCall;
val* NEW_nit__AExternCalls(const struct type* type);
extern const struct type type_nit__AExternCalls;
extern const int COLOR_nit__parser_prod__AExternCalls__init_aexterncalls;
val* NEW_nit__ASuperExternCall(const struct type* type);
extern const struct type type_nit__ASuperExternCall;
extern const int COLOR_nit__parser_prod__ASuperExternCall__init_asuperexterncall;
val* NEW_nit__ALocalPropExternCall(const struct type* type);
extern const struct type type_nit__ALocalPropExternCall;
extern const int COLOR_nit__parser_prod__ALocalPropExternCall__init_alocalpropexterncall;
extern const struct type type_nullable__nit__TDot;
val* NEW_nit__AFullPropExternCall(const struct type* type);
extern const struct type type_nit__AFullPropExternCall;
extern const int COLOR_nit__parser_prod__AFullPropExternCall__init_afullpropexterncall;
val* NEW_nit__AInitPropExternCall(const struct type* type);
extern const struct type type_nit__AInitPropExternCall;
extern const int COLOR_nit__parser_prod__AInitPropExternCall__init_ainitpropexterncall;
extern const struct type type_nullable__nit__TKwas;
val* NEW_nit__ACastAsExternCall(const struct type* type);
extern const struct type type_nit__ACastAsExternCall;
extern const int COLOR_nit__parser_prod__ACastAsExternCall__init_acastasexterncall;
extern const struct type type_nullable__nit__TKwnullable;
val* NEW_nit__AAsNullableExternCall(const struct type* type);
extern const struct type type_nit__AAsNullableExternCall;
extern const int COLOR_nit__parser_prod__AAsNullableExternCall__init_aasnullableexterncall;
extern const struct type type_nullable__nit__TKwnot;
val* NEW_nit__AAsNotNullableExternCall(const struct type* type);
extern const struct type type_nit__AAsNotNullableExternCall;
extern const int COLOR_nit__parser_prod__AAsNotNullableExternCall__init_aasnotnullableexterncall;
extern const struct type type_nullable__nit__TKwin;
extern const struct type type_nullable__nit__TString;
val* NEW_nit__AInLanguage(const struct type* type);
extern const struct type type_nit__AInLanguage;
extern const int COLOR_nit__parser_prod__AInLanguage__init_ainlanguage;
extern const struct type type_nullable__nit__TExternCodeSegment;
val* NEW_nit__AExternCodeBlock(const struct type* type);
extern const struct type type_nit__AExternCodeBlock;
extern const int COLOR_nit__parser_prod__AExternCodeBlock__init_aexterncodeblock;
extern const struct type type_nullable__nit__AInLanguage;
val* NEW_nit__AType(const struct type* type);
extern const struct type type_nit__AType;
extern const int COLOR_nit__parser_prod__AType__init_atype;
val* NEW_nit__ABlockExpr(const struct type* type);
extern const struct type type_nit__ABlockExpr;
extern const int COLOR_nit__parser_prod__ABlockExpr__init_ablockexpr;
extern const struct type type_nullable__nit__TKwreturn;
val* NEW_nit__AReturnExpr(const struct type* type);
extern const struct type type_nit__AReturnExpr;
extern const int COLOR_nit__parser_prod__AReturnExpr__init_areturnexpr;
extern const struct type type_nullable__nit__TKwbreak;
val* NEW_nit__ABreakExpr(const struct type* type);
extern const struct type type_nit__ABreakExpr;
extern const int COLOR_nit__parser_prod__ABreakExpr__init_abreakexpr;
extern const struct type type_nullable__nit__ALabel;
extern const struct type type_nullable__nit__TKwabort;
val* NEW_nit__AAbortExpr(const struct type* type);
extern const struct type type_nit__AAbortExpr;
extern const int COLOR_nit__parser_prod__AAbortExpr__init_aabortexpr;
extern const struct type type_nullable__nit__TKwcontinue;
val* NEW_nit__AContinueExpr(const struct type* type);
extern const struct type type_nit__AContinueExpr;
extern const int COLOR_nit__parser_prod__AContinueExpr__init_acontinueexpr;
extern const struct type type_nullable__nit__AExprs;
val* NEW_nit__ACallExpr(const struct type* type);
extern const struct type type_nit__ACallExpr;
extern const int COLOR_nit__parser_prod__ACallExpr__init_acallexpr;
val* NEW_nit__AImplicitSelfExpr(const struct type* type);
extern const struct type type_nit__AImplicitSelfExpr;
extern const int COLOR_nit__parser_prod__AImplicitSelfExpr__init_aimplicitselfexpr;
extern const struct type type_nullable__nit__AQualified;
val* NEW_nit__ASuperExpr(const struct type* type);
extern const struct type type_nit__ASuperExpr;
extern const int COLOR_nit__parser_prod__ASuperExpr__init_asuperexpr;
val* NEW_nit__AInitExpr(const struct type* type);
extern const struct type type_nit__AInitExpr;
extern const int COLOR_nit__parser_prod__AInitExpr__init_ainitexpr;
extern const struct type type_nullable__nit__TKwdebug;
val* NEW_nit__ADebugTypeExpr(const struct type* type);
extern const struct type type_nit__ADebugTypeExpr;
extern const int COLOR_nit__parser_prod__ADebugTypeExpr__init_adebugtypeexpr;
extern const struct type type_nullable__nit__TKwlabel;
val* NEW_nit__ALabel(const struct type* type);
extern const struct type type_nit__ALabel;
extern const int COLOR_nit__parser_prod__ALabel__init_alabel;
val* NEW_nit__AVardeclExpr(const struct type* type);
extern const struct type type_nit__AVardeclExpr;
extern const int COLOR_nit__parser_prod__AVardeclExpr__init_avardeclexpr;
extern const struct type type_nullable__nit__TAttrid;
val* NEW_nit__AAttrAssignExpr(const struct type* type);
extern const struct type type_nit__AAttrAssignExpr;
extern const int COLOR_nit__parser_prod__AAttrAssignExpr__init_aattrassignexpr;
val* NEW_nit__ACallAssignExpr(const struct type* type);
extern const struct type type_nit__ACallAssignExpr;
extern const int COLOR_nit__parser_prod__ACallAssignExpr__init_acallassignexpr;
val* NEW_nit__AListExprs(const struct type* type);
extern const struct type type_nit__AListExprs;
extern const int COLOR_nit__parser_prod__AListExprs__init_alistexprs;
val* NEW_nit__ABraAssignExpr(const struct type* type);
extern const struct type type_nit__ABraAssignExpr;
extern const int COLOR_nit__parser_prod__ABraAssignExpr__init_abraassignexpr;
extern const struct type type_nullable__nit__AAssignOp;
val* NEW_nit__AAttrReassignExpr(const struct type* type);
extern const struct type type_nit__AAttrReassignExpr;
extern const int COLOR_nit__parser_prod__AAttrReassignExpr__init_aattrreassignexpr;
val* NEW_nit__ACallReassignExpr(const struct type* type);
extern const struct type type_nit__ACallReassignExpr;
extern const int COLOR_nit__parser_prod__ACallReassignExpr__init_acallreassignexpr;
val* NEW_nit__ABraReassignExpr(const struct type* type);
extern const struct type type_nit__ABraReassignExpr;
extern const int COLOR_nit__parser_prod__ABraReassignExpr__init_abrareassignexpr;
extern const struct type type_nullable__nit__TPluseq;
val* NEW_nit__APlusAssignOp(const struct type* type);
extern const struct type type_nit__APlusAssignOp;
extern const int COLOR_nit__parser_prod__APlusAssignOp__init_aplusassignop;
extern const struct type type_nullable__nit__TMinuseq;
val* NEW_nit__AMinusAssignOp(const struct type* type);
extern const struct type type_nit__AMinusAssignOp;
extern const int COLOR_nit__parser_prod__AMinusAssignOp__init_aminusassignop;
extern const struct type type_nullable__nit__TStareq;
val* NEW_nit__AStarAssignOp(const struct type* type);
extern const struct type type_nit__AStarAssignOp;
extern const int COLOR_nit__parser_prod__AStarAssignOp__init_astarassignop;
extern const struct type type_nullable__nit__TSlasheq;
val* NEW_nit__ASlashAssignOp(const struct type* type);
extern const struct type type_nit__ASlashAssignOp;
extern const int COLOR_nit__parser_prod__ASlashAssignOp__init_aslashassignop;
extern const struct type type_nullable__nit__TPercenteq;
val* NEW_nit__APercentAssignOp(const struct type* type);
extern const struct type type_nit__APercentAssignOp;
extern const int COLOR_nit__parser_prod__APercentAssignOp__init_apercentassignop;
extern const struct type type_nullable__nit__TStarstareq;
val* NEW_nit__AStarstarAssignOp(const struct type* type);
extern const struct type type_nit__AStarstarAssignOp;
extern const int COLOR_nit__parser_prod__AStarstarAssignOp__init_astarstarassignop;
extern const struct type type_nullable__nit__TPipeeq;
val* NEW_nit__APipeAssignOp(const struct type* type);
extern const struct type type_nit__APipeAssignOp;
extern const int COLOR_nit__parser_prod__APipeAssignOp__init_apipeassignop;
extern const struct type type_nullable__nit__TCareteq;
val* NEW_nit__ACaretAssignOp(const struct type* type);
extern const struct type type_nit__ACaretAssignOp;
extern const int COLOR_nit__parser_prod__ACaretAssignOp__init_acaretassignop;
extern const struct type type_nullable__nit__TAmpeq;
val* NEW_nit__AAmpAssignOp(const struct type* type);
extern const struct type type_nit__AAmpAssignOp;
extern const int COLOR_nit__parser_prod__AAmpAssignOp__init_aampassignop;
extern const struct type type_nullable__nit__TLleq;
val* NEW_nit__ALlAssignOp(const struct type* type);
extern const struct type type_nit__ALlAssignOp;
extern const int COLOR_nit__parser_prod__ALlAssignOp__init_allassignop;
extern const struct type type_nullable__nit__TGgeq;
val* NEW_nit__AGgAssignOp(const struct type* type);
extern const struct type type_nit__AGgAssignOp;
extern const int COLOR_nit__parser_prod__AGgAssignOp__init_aggassignop;
extern const struct type type_nullable__nit__TKwdo;
val* NEW_nit__ADoExpr(const struct type* type);
extern const struct type type_nit__ADoExpr;
extern const int COLOR_nit__parser_prod__ADoExpr__init_adoexpr;
extern const struct type type_nullable__nit__TKwif;
val* NEW_nit__AIfExpr(const struct type* type);
extern const struct type type_nit__AIfExpr;
extern const int COLOR_nit__parser_prod__AIfExpr__init_aifexpr;
extern const struct type type_nullable__nit__TKwloop;
val* NEW_nit__ALoopExpr(const struct type* type);
extern const struct type type_nit__ALoopExpr;
extern const int COLOR_nit__parser_prod__ALoopExpr__init_aloopexpr;
extern const struct type type_nullable__nit__TKwwhile;
val* NEW_nit__AWhileExpr(const struct type* type);
extern const struct type type_nit__AWhileExpr;
extern const int COLOR_nit__parser_prod__AWhileExpr__init_awhileexpr;
extern const struct type type_nullable__nit__TKwfor;
val* NEW_nit__AForExpr(const struct type* type);
extern const struct type type_nit__AForExpr;
extern const int COLOR_nit__parser_prod__AForExpr__init_aforexpr;
extern const struct type type_nullable__nit__TKwwith;
val* NEW_nit__AWithExpr(const struct type* type);
extern const struct type type_nit__AWithExpr;
extern const int COLOR_nit__parser_prod__AWithExpr__init_awithexpr;
extern const struct type type_nullable__nit__TKwassert;
val* NEW_nit__AAssertExpr(const struct type* type);
extern const struct type type_nit__AAssertExpr;
extern const int COLOR_nit__parser_prod__AAssertExpr__init_aassertexpr;
extern const struct type type_nullable__nit__TKwthen;
extern const struct type type_nullable__nit__TKwelse;
val* NEW_nit__AIfexprExpr(const struct type* type);
extern const struct type type_nit__AIfexprExpr;
extern const int COLOR_nit__parser_prod__AIfexprExpr__init_aifexprexpr;
extern const struct type type_nullable__nit__TKwor;
val* NEW_nit__AOrExpr(const struct type* type);
extern const struct type type_nit__AOrExpr;
extern const int COLOR_nit__parser_prod__AOrExpr__init_aorexpr;
extern const struct type type_nullable__nit__TKwand;
val* NEW_nit__AAndExpr(const struct type* type);
extern const struct type type_nit__AAndExpr;
extern const int COLOR_nit__parser_prod__AAndExpr__init_aandexpr;
val* NEW_nit__AOrElseExpr(const struct type* type);
extern const struct type type_nit__AOrElseExpr;
extern const int COLOR_nit__parser_prod__AOrElseExpr__init_aorelseexpr;
extern const struct type type_nullable__nit__TKwimplies;
val* NEW_nit__AImpliesExpr(const struct type* type);
extern const struct type type_nit__AImpliesExpr;
extern const int COLOR_nit__parser_prod__AImpliesExpr__init_aimpliesexpr;
val* NEW_nit__ANotExpr(const struct type* type);
extern const struct type type_nit__ANotExpr;
extern const int COLOR_nit__parser_prod__ANotExpr__init_anotexpr;
val* NEW_nit__AEqExpr(const struct type* type);
extern const struct type type_nit__AEqExpr;
extern const int COLOR_nit__parser_prod__AEqExpr__init_aeqexpr;
val* NEW_nit__ANeExpr(const struct type* type);
extern const struct type type_nit__ANeExpr;
extern const int COLOR_nit__parser_prod__ANeExpr__init_aneexpr;
val* NEW_nit__ALtExpr(const struct type* type);
extern const struct type type_nit__ALtExpr;
extern const int COLOR_nit__parser_prod__ALtExpr__init_altexpr;
val* NEW_nit__ALeExpr(const struct type* type);
extern const struct type type_nit__ALeExpr;
extern const int COLOR_nit__parser_prod__ALeExpr__init_aleexpr;
val* NEW_nit__AGtExpr(const struct type* type);
extern const struct type type_nit__AGtExpr;
extern const int COLOR_nit__parser_prod__AGtExpr__init_agtexpr;
val* NEW_nit__AGeExpr(const struct type* type);
extern const struct type type_nit__AGeExpr;
extern const int COLOR_nit__parser_prod__AGeExpr__init_ageexpr;
val* NEW_nit__AStarshipExpr(const struct type* type);
extern const struct type type_nit__AStarshipExpr;
extern const int COLOR_nit__parser_prod__AStarshipExpr__init_astarshipexpr;
extern const struct type type_nullable__nit__TKwisa;
val* NEW_nit__AIsaExpr(const struct type* type);
extern const struct type type_nit__AIsaExpr;
extern const int COLOR_nit__parser_prod__AIsaExpr__init_aisaexpr;
val* NEW_nit__APipeExpr(const struct type* type);
extern const struct type type_nit__APipeExpr;
extern const int COLOR_nit__parser_prod__APipeExpr__init_apipeexpr;
val* NEW_nit__ACaretExpr(const struct type* type);
extern const struct type type_nit__ACaretExpr;
extern const int COLOR_nit__parser_prod__ACaretExpr__init_acaretexpr;
val* NEW_nit__AAmpExpr(const struct type* type);
extern const struct type type_nit__AAmpExpr;
extern const int COLOR_nit__parser_prod__AAmpExpr__init_aampexpr;
val* NEW_nit__ALlExpr(const struct type* type);
extern const struct type type_nit__ALlExpr;
extern const int COLOR_nit__parser_prod__ALlExpr__init_allexpr;
val* NEW_nit__AGgExpr(const struct type* type);
extern const struct type type_nit__AGgExpr;
extern const int COLOR_nit__parser_prod__AGgExpr__init_aggexpr;
val* NEW_nit__APlusExpr(const struct type* type);
extern const struct type type_nit__APlusExpr;
extern const int COLOR_nit__parser_prod__APlusExpr__init_aplusexpr;
val* NEW_nit__AMinusExpr(const struct type* type);
extern const struct type type_nit__AMinusExpr;
extern const int COLOR_nit__parser_prod__AMinusExpr__init_aminusexpr;
val* NEW_nit__AStarExpr(const struct type* type);
extern const struct type type_nit__AStarExpr;
extern const int COLOR_nit__parser_prod__AStarExpr__init_astarexpr;
val* NEW_nit__ASlashExpr(const struct type* type);
extern const struct type type_nit__ASlashExpr;
extern const int COLOR_nit__parser_prod__ASlashExpr__init_aslashexpr;
val* NEW_nit__APercentExpr(const struct type* type);
extern const struct type type_nit__APercentExpr;
extern const int COLOR_nit__parser_prod__APercentExpr__init_apercentexpr;
val* NEW_nit__AStarstarExpr(const struct type* type);
extern const struct type type_nit__AStarstarExpr;
extern const int COLOR_nit__parser_prod__AStarstarExpr__init_astarstarexpr;
val* NEW_nit__AUminusExpr(const struct type* type);
extern const struct type type_nit__AUminusExpr;
extern const int COLOR_nit__parser_prod__AUminusExpr__init_auminusexpr;
val* NEW_nit__AUplusExpr(const struct type* type);
extern const struct type type_nit__AUplusExpr;
extern const int COLOR_nit__parser_prod__AUplusExpr__init_auplusexpr;
val* NEW_nit__AUtildeExpr(const struct type* type);
extern const struct type type_nit__AUtildeExpr;
extern const int COLOR_nit__parser_prod__AUtildeExpr__init_autildeexpr;
extern const struct type type_nullable__nit__TKwonce;
val* NEW_nit__AOnceExpr(const struct type* type);
extern const struct type type_nit__AOnceExpr;
extern const int COLOR_nit__parser_prod__AOnceExpr__init_aonceexpr;
val* NEW_nit__ANewExpr(const struct type* type);
extern const struct type type_nit__ANewExpr;
extern const int COLOR_nit__parser_prod__ANewExpr__init_anewexpr;
extern const struct type type_nullable__nit__TKwisset;
val* NEW_nit__AIssetAttrExpr(const struct type* type);
extern const struct type type_nit__AIssetAttrExpr;
extern const int COLOR_nit__parser_prod__AIssetAttrExpr__init_aissetattrexpr;
val* NEW_nit__AAttrExpr(const struct type* type);
extern const struct type type_nit__AAttrExpr;
extern const int COLOR_nit__parser_prod__AAttrExpr__init_aattrexpr;
val* NEW_nit__ABraExpr(const struct type* type);
extern const struct type type_nit__ABraExpr;
extern const int COLOR_nit__parser_prod__ABraExpr__init_abraexpr;
val* NEW_nit__AAsCastExpr(const struct type* type);
extern const struct type type_nit__AAsCastExpr;
extern const int COLOR_nit__parser_prod__AAsCastExpr__init_aascastexpr;
extern const struct type type_nullable__nit__TKwnull;
val* NEW_nit__AAsNotnullExpr(const struct type* type);
extern const struct type type_nit__AAsNotnullExpr;
extern const int COLOR_nit__parser_prod__AAsNotnullExpr__init_aasnotnullexpr;
val* NEW_nit__AVarargExpr(const struct type* type);
extern const struct type type_nit__AVarargExpr;
extern const int COLOR_nit__parser_prod__AVarargExpr__init_avarargexpr;
val* NEW_nit__ANamedargExpr(const struct type* type);
extern const struct type type_nit__ANamedargExpr;
extern const int COLOR_nit__parser_prod__ANamedargExpr__init_anamedargexpr;
extern const struct type type_nullable__nit__TKwself;
val* NEW_nit__ASelfExpr(const struct type* type);
extern const struct type type_nit__ASelfExpr;
extern const int COLOR_nit__parser_prod__ASelfExpr__init_aselfexpr;
extern const struct type type_nullable__nit__TKwtrue;
val* NEW_nit__ATrueExpr(const struct type* type);
extern const struct type type_nit__ATrueExpr;
extern const int COLOR_nit__parser_prod__ATrueExpr__init_atrueexpr;
extern const struct type type_nullable__nit__TKwfalse;
val* NEW_nit__AFalseExpr(const struct type* type);
extern const struct type type_nit__AFalseExpr;
extern const int COLOR_nit__parser_prod__AFalseExpr__init_afalseexpr;
val* NEW_nit__ANullExpr(const struct type* type);
extern const struct type type_nit__ANullExpr;
extern const int COLOR_nit__parser_prod__ANullExpr__init_anullexpr;
extern const struct type type_nullable__nit__TNumber;
val* NEW_nit__ADecIntExpr(const struct type* type);
extern const struct type type_nit__ADecIntExpr;
extern const int COLOR_nit__parser_prod__ADecIntExpr__init_adecintexpr;
extern const struct type type_nullable__nit__THexNumber;
val* NEW_nit__AHexIntExpr(const struct type* type);
extern const struct type type_nit__AHexIntExpr;
extern const int COLOR_nit__parser_prod__AHexIntExpr__init_ahexintexpr;
extern const struct type type_nullable__nit__TFloat;
val* NEW_nit__AFloatExpr(const struct type* type);
extern const struct type type_nit__AFloatExpr;
extern const int COLOR_nit__parser_prod__AFloatExpr__init_afloatexpr;
extern const struct type type_nullable__nit__TChar;
val* NEW_nit__ACharExpr(const struct type* type);
extern const struct type type_nit__ACharExpr;
extern const int COLOR_nit__parser_prod__ACharExpr__init_acharexpr;
val* NEW_nit__AStringExpr(const struct type* type);
extern const struct type type_nit__AStringExpr;
extern const int COLOR_nit__parser_prod__AStringExpr__init_astringexpr;
val* NEW_nit__ACrangeExpr(const struct type* type);
extern const struct type type_nit__ACrangeExpr;
extern const int COLOR_nit__parser_prod__ACrangeExpr__init_acrangeexpr;
val* NEW_nit__AOrangeExpr(const struct type* type);
extern const struct type type_nit__AOrangeExpr;
extern const int COLOR_nit__parser_prod__AOrangeExpr__init_aorangeexpr;
val* NEW_nit__AArrayExpr(const struct type* type);
extern const struct type type_nit__AArrayExpr;
extern const int COLOR_nit__parser_prod__AArrayExpr__init_aarrayexpr;
val* NEW_nit__AParExpr(const struct type* type);
extern const struct type type_nit__AParExpr;
extern const int COLOR_nit__parser_prod__AParExpr__init_aparexpr;
val* NEW_nit__AManyExpr(const struct type* type);
extern const struct type type_nit__AManyExpr;
extern const int COLOR_nit__parser_prod__AManyExpr__init_amanyexpr;
val* NEW_nit__ASuperstringExpr(const struct type* type);
extern const struct type type_nit__ASuperstringExpr;
extern const int COLOR_nit__parser_prod__ASuperstringExpr__init_asuperstringexpr;
extern const struct type type_nullable__nit__TStartString;
val* NEW_nit__AStartStringExpr(const struct type* type);
extern const struct type type_nit__AStartStringExpr;
extern const int COLOR_nit__parser_prod__AStartStringExpr__init_astartstringexpr;
extern const struct type type_nullable__nit__TMidString;
val* NEW_nit__AMidStringExpr(const struct type* type);
extern const struct type type_nit__AMidStringExpr;
extern const int COLOR_nit__parser_prod__AMidStringExpr__init_amidstringexpr;
extern const struct type type_nullable__nit__TEndString;
val* NEW_nit__AEndStringExpr(const struct type* type);
extern const struct type type_nit__AEndStringExpr;
extern const int COLOR_nit__parser_prod__AEndStringExpr__init_aendstringexpr;
extern const struct type type_nullable__nit__TAt;
extern const struct type type_nullable__nit__AAnnotation;
val* NEW_nit__AAnnotations(const struct type* type);
extern const struct type type_nit__AAnnotations;
extern const int COLOR_nit__parser_prod__AAnnotations__init_aannotations;
extern const struct type type_nullable__nit__AAtid;
val* NEW_nit__AAnnotation(const struct type* type);
extern const struct type type_nit__AAnnotation;
extern const int COLOR_nit__parser_prod__AAnnotation__init_aannotation;
val* NEW_nit__AAnnotPropdef(const struct type* type);
extern const struct type type_nit__AAnnotPropdef;
extern const int COLOR_nit__parser_prod__AAnnotPropdef__init_aannotpropdef;
val* NEW_nit__ATypeExpr(const struct type* type);
extern const struct type type_nit__ATypeExpr;
extern const int COLOR_nit__parser_prod__ATypeExpr__init_atypeexpr;
val* NEW_nit__AMethidExpr(const struct type* type);
extern const struct type type_nit__AMethidExpr;
extern const int COLOR_nit__parser_prod__AMethidExpr__init_amethidexpr;
val* NEW_nit__AAtExpr(const struct type* type);
extern const struct type type_nit__AAtExpr;
extern const int COLOR_nit__parser_prod__AAtExpr__init_aatexpr;
val* NEW_nit__AIdAtid(const struct type* type);
extern const struct type type_nit__AIdAtid;
extern const int COLOR_nit__parser_prod__AIdAtid__init_aidatid;
val* NEW_nit__AKwexternAtid(const struct type* type);
extern const struct type type_nit__AKwexternAtid;
extern const int COLOR_nit__parser_prod__AKwexternAtid__init_akwexternatid;
val* NEW_nit__AKwabstractAtid(const struct type* type);
extern const struct type type_nit__AKwabstractAtid;
extern const int COLOR_nit__parser_prod__AKwabstractAtid__init_akwabstractatid;
val* NEW_nit__AParExprs(const struct type* type);
extern const struct type type_nit__AParExprs;
extern const int COLOR_nit__parser_prod__AParExprs__init_aparexprs;
val* NEW_nit__ABraExprs(const struct type* type);
extern const struct type type_nit__ABraExprs;
extern const int COLOR_nit__parser_prod__ABraExprs__init_abraexprs;
val* NEW_nit__AModuleName(const struct type* type);
extern const struct type type_nit__AModuleName;
extern const int COLOR_nit__parser_prod__AModuleName__init_amodulename;
extern const struct type type_nullable__nit__TQuad;
val* NEW_nit__AQualified(const struct type* type);
extern const struct type type_nit__AQualified;
extern const int COLOR_nit__parser_prod__AQualified__init_aqualified;
val* NEW_nit__ADoc(const struct type* type);
extern const struct type type_nit__ADoc;
extern const int COLOR_nit__parser_prod__ADoc__init_adoc;
