#include "nit.common.h"
val* NEW_nit__SourceFile(const struct type* type);
extern const struct type type_nit__SourceFile;
val* standard___standard__NativeString___to_s_with_length(char* self, long p0);
extern const int COLOR_nit__location__SourceFile__from_string;
val* NEW_nit__Lexer(const struct type* type);
extern const struct type type_nit__Lexer;
extern const int COLOR_nit__lexer_work__Lexer__file_61d;
extern const int COLOR_standard__kernel__Object__init;
val* NEW_nit__Parser(const struct type* type);
extern const struct type type_nit__Parser;
extern const int COLOR_nit__parser_work__Parser__lexer_61d;
extern const int COLOR_nit__parser_work__Parser__parse;
extern const int COLOR_nit__parser_nodes__Start__n_eof;
extern const struct type type_nit__AError;
val* NEW_standard__NativeArray(int length, const struct type* type);
extern const struct type type_standard__NativeArray__standard__String;
extern const int COLOR_nit__lexer_work__AError__message;
extern const int COLOR_standard__string__NativeArray__native_to_s;
extern const int COLOR_nit__toolcontext__ToolContext__fatal_error;
extern const char FILE_nit__parser_util[];
extern const int COLOR_nit__parser_nodes__Start__n_base;
extern const int COLOR_nit__parser_util__ToolContext__parse_module;
extern const int COLOR_nit__parser_nodes__AModule__n_classdefs;
extern const int COLOR_standard__abstract_collection__Collection__length;
extern const int COLOR_standard__abstract_collection__Collection__first;
extern const int COLOR_nit__parser_util__ToolContext__parse_classdef;
extern const int COLOR_nit__parser_nodes__AClassdef__n_propdefs;
extern const struct type type_nit__AMethPropdef;
extern const int COLOR_nit__parser_nodes__AMethPropdef__n_block;
extern const struct type type_nit__ABlockExpr;
extern const int COLOR_nit__parser_nodes__ABlockExpr__n_expr;
extern const struct type type_nit__ADoExpr;
extern const int COLOR_nit__parser_nodes__ADoExpr__n_block;
extern const struct type type_nit__AVardeclExpr;
extern const int COLOR_nit__parser_nodes__AVardeclExpr__n_expr;
extern const struct type type_nit__AStdClassdef;
val* NEW_nit__InjectedLexer(const struct type* type);
extern const struct type type_nit__InjectedLexer;
extern const int COLOR_nit__parser_util__InjectedLexer__injected_before;
val* NEW_nit__TKwvar(const struct type* type);
extern const struct type type_nit__TKwvar;
extern const int COLOR_standard__abstract_collection__SimpleCollection__add;
val* NEW_nit__TId(const struct type* type);
extern const struct type type_nit__TId;
val* NEW_nit__TColumn(const struct type* type);
extern const struct type type_nit__TColumn;
val* NEW_nit__TClassid(const struct type* type);
extern const struct type type_nit__TClassid;
val* NEW_nit__TObra(const struct type* type);
extern const struct type type_nit__TObra;
extern const int COLOR_nit__parser_util__InjectedLexer__injected_after;
val* NEW_nit__TCbra(const struct type* type);
extern const struct type type_nit__TCbra;
extern const int COLOR_nit__parser_nodes__AVardeclExpr__n_type;
extern const int COLOR_nit__parser_nodes__AType__n_types;
extern const int COLOR_nit__parser_nodes__ANode__parent_61d;
extern const int COLOR_nit__lexer_work__Lexer__next;
extern const struct type type_nit__EOF;
val* NEW_nit__TAssign(const struct type* type);
extern const struct type type_nit__TAssign;
val* NEW_nit__TOpar(const struct type* type);
extern const struct type type_nit__TOpar;
val* NEW_nit__TCpar(const struct type* type);
extern const struct type type_nit__TCpar;
extern const struct type type_nit__AParExpr;
extern const int COLOR_nit__parser_nodes__AParExpr__n_expr;
extern const int COLOR_nit__parser_nodes__ANode__location;
extern const int COLOR_standard__kernel__Comparable___62d;
val* NEW_nit__TKwdo(const struct type* type);
extern const struct type type_nit__TKwdo;
val* NEW_nit__TEol(const struct type* type);
extern const struct type type_nit__TEol;
val* NEW_nit__TKwend(const struct type* type);
extern const struct type type_nit__TKwend;
extern const int COLOR_nit__parser_nodes__ABlockExpr__n_kwend_61d;
val* NEW_standard__Array(const struct type* type);
extern const struct type type_standard__Array__standard__Object;
extern const struct type type_standard__NativeArray__standard__Object;
extern const int COLOR_standard__array__Array__with_native;
extern const int COLOR_standard__file__Sys__printn;
extern const int COLOR_standard__file__Sys__stdin;
extern const int COLOR_standard__stream__Reader__read_line;
extern const int COLOR_standard__kernel__Object___61d_61d;
extern const int COLOR_standard__string__Text__chars;
val* NEW_nit__TString(const struct type* type);
extern const struct type type_nit__TString;
extern const int COLOR_nit__parser_nodes__Token__text_61d;
extern const int COLOR_standard__string__String___43d;
extern const int COLOR_nit__parser_util__ToolContext__parse_something;
extern const struct type type_nit__AParserError;
extern const int COLOR_nit__lexer_work__AParserError__token;
extern const int COLOR_standard__string__Text__length;
extern const int COLOR_standard__string__String___42d;
extern const int COLOR_nit__parser_util__InjectedLexer___injected_before;
extern const int COLOR_nit__parser_util__InjectedLexer___injected_after;
extern const int COLOR_nit__parser_util__InjectedLexer___is_finished;
extern const int COLOR_standard__abstract_collection__Collection__is_empty;
extern const int COLOR_standard__abstract_collection__Sequence__shift;
extern const int COLOR_nit__parser_util__InjectedLexer__is_finished;
extern const int COLOR_nit___nit__InjectedLexer___nit__lexer_work__Lexer__get_token;
extern const int COLOR_standard__abstract_collection__Sequence__push;
extern const int COLOR_nit__parser_util__InjectedLexer__is_finished_61d;
