#include "nit.common.h"
extern const int COLOR_standard__kernel__Object__init;
extern const int COLOR_nit__parser_nodes__ANode___location;
val* NEW_nit__TEol(const struct type* type);
extern const struct type type_nit__TEol;
extern const int COLOR_nit__lexer__TEol__init_tk;
val* NEW_nit__TComment(const struct type* type);
extern const struct type type_nit__TComment;
extern const int COLOR_nit__lexer__TComment__init_tk;
val* NEW_nit__TKwpackage(const struct type* type);
extern const struct type type_nit__TKwpackage;
extern const int COLOR_nit__lexer__TKwpackage__init_tk;
val* NEW_nit__TKwmodule(const struct type* type);
extern const struct type type_nit__TKwmodule;
extern const int COLOR_nit__lexer__TKwmodule__init_tk;
val* NEW_nit__TKwimport(const struct type* type);
extern const struct type type_nit__TKwimport;
extern const int COLOR_nit__lexer__TKwimport__init_tk;
val* NEW_nit__TKwclass(const struct type* type);
extern const struct type type_nit__TKwclass;
extern const int COLOR_nit__lexer__TKwclass__init_tk;
val* NEW_nit__TKwabstract(const struct type* type);
extern const struct type type_nit__TKwabstract;
extern const int COLOR_nit__lexer__TKwabstract__init_tk;
val* NEW_nit__TKwinterface(const struct type* type);
extern const struct type type_nit__TKwinterface;
extern const int COLOR_nit__lexer__TKwinterface__init_tk;
val* NEW_nit__TKwenum(const struct type* type);
extern const struct type type_nit__TKwenum;
extern const int COLOR_nit__lexer__TKwenum__init_tk;
val* NEW_nit__TKwend(const struct type* type);
extern const struct type type_nit__TKwend;
extern const int COLOR_nit__lexer__TKwend__init_tk;
val* NEW_nit__TKwmeth(const struct type* type);
extern const struct type type_nit__TKwmeth;
extern const int COLOR_nit__lexer__TKwmeth__init_tk;
val* NEW_nit__TKwtype(const struct type* type);
extern const struct type type_nit__TKwtype;
extern const int COLOR_nit__lexer__TKwtype__init_tk;
val* NEW_nit__TKwinit(const struct type* type);
extern const struct type type_nit__TKwinit;
extern const int COLOR_nit__lexer__TKwinit__init_tk;
val* NEW_nit__TKwredef(const struct type* type);
extern const struct type type_nit__TKwredef;
extern const int COLOR_nit__lexer__TKwredef__init_tk;
val* NEW_nit__TKwis(const struct type* type);
extern const struct type type_nit__TKwis;
extern const int COLOR_nit__lexer__TKwis__init_tk;
val* NEW_nit__TKwdo(const struct type* type);
extern const struct type type_nit__TKwdo;
extern const int COLOR_nit__lexer__TKwdo__init_tk;
val* NEW_nit__TKwvar(const struct type* type);
extern const struct type type_nit__TKwvar;
extern const int COLOR_nit__lexer__TKwvar__init_tk;
val* NEW_nit__TKwextern(const struct type* type);
extern const struct type type_nit__TKwextern;
extern const int COLOR_nit__lexer__TKwextern__init_tk;
val* NEW_nit__TKwpublic(const struct type* type);
extern const struct type type_nit__TKwpublic;
extern const int COLOR_nit__lexer__TKwpublic__init_tk;
val* NEW_nit__TKwprotected(const struct type* type);
extern const struct type type_nit__TKwprotected;
extern const int COLOR_nit__lexer__TKwprotected__init_tk;
val* NEW_nit__TKwprivate(const struct type* type);
extern const struct type type_nit__TKwprivate;
extern const int COLOR_nit__lexer__TKwprivate__init_tk;
val* NEW_nit__TKwintrude(const struct type* type);
extern const struct type type_nit__TKwintrude;
extern const int COLOR_nit__lexer__TKwintrude__init_tk;
val* NEW_nit__TKwif(const struct type* type);
extern const struct type type_nit__TKwif;
extern const int COLOR_nit__lexer__TKwif__init_tk;
val* NEW_nit__TKwthen(const struct type* type);
extern const struct type type_nit__TKwthen;
extern const int COLOR_nit__lexer__TKwthen__init_tk;
val* NEW_nit__TKwelse(const struct type* type);
extern const struct type type_nit__TKwelse;
extern const int COLOR_nit__lexer__TKwelse__init_tk;
val* NEW_nit__TKwwhile(const struct type* type);
extern const struct type type_nit__TKwwhile;
extern const int COLOR_nit__lexer__TKwwhile__init_tk;
val* NEW_nit__TKwloop(const struct type* type);
extern const struct type type_nit__TKwloop;
extern const int COLOR_nit__lexer__TKwloop__init_tk;
val* NEW_nit__TKwfor(const struct type* type);
extern const struct type type_nit__TKwfor;
extern const int COLOR_nit__lexer__TKwfor__init_tk;
val* NEW_nit__TKwin(const struct type* type);
extern const struct type type_nit__TKwin;
extern const int COLOR_nit__lexer__TKwin__init_tk;
val* NEW_nit__TKwand(const struct type* type);
extern const struct type type_nit__TKwand;
extern const int COLOR_nit__lexer__TKwand__init_tk;
val* NEW_nit__TKwor(const struct type* type);
extern const struct type type_nit__TKwor;
extern const int COLOR_nit__lexer__TKwor__init_tk;
val* NEW_nit__TKwnot(const struct type* type);
extern const struct type type_nit__TKwnot;
extern const int COLOR_nit__lexer__TKwnot__init_tk;
val* NEW_nit__TKwimplies(const struct type* type);
extern const struct type type_nit__TKwimplies;
extern const int COLOR_nit__lexer__TKwimplies__init_tk;
val* NEW_nit__TKwreturn(const struct type* type);
extern const struct type type_nit__TKwreturn;
extern const int COLOR_nit__lexer__TKwreturn__init_tk;
val* NEW_nit__TKwcontinue(const struct type* type);
extern const struct type type_nit__TKwcontinue;
extern const int COLOR_nit__lexer__TKwcontinue__init_tk;
val* NEW_nit__TKwbreak(const struct type* type);
extern const struct type type_nit__TKwbreak;
extern const int COLOR_nit__lexer__TKwbreak__init_tk;
val* NEW_nit__TKwabort(const struct type* type);
extern const struct type type_nit__TKwabort;
extern const int COLOR_nit__lexer__TKwabort__init_tk;
val* NEW_nit__TKwassert(const struct type* type);
extern const struct type type_nit__TKwassert;
extern const int COLOR_nit__lexer__TKwassert__init_tk;
val* NEW_nit__TKwnew(const struct type* type);
extern const struct type type_nit__TKwnew;
extern const int COLOR_nit__lexer__TKwnew__init_tk;
val* NEW_nit__TKwisa(const struct type* type);
extern const struct type type_nit__TKwisa;
extern const int COLOR_nit__lexer__TKwisa__init_tk;
val* NEW_nit__TKwonce(const struct type* type);
extern const struct type type_nit__TKwonce;
extern const int COLOR_nit__lexer__TKwonce__init_tk;
val* NEW_nit__TKwsuper(const struct type* type);
extern const struct type type_nit__TKwsuper;
extern const int COLOR_nit__lexer__TKwsuper__init_tk;
val* NEW_nit__TKwself(const struct type* type);
extern const struct type type_nit__TKwself;
extern const int COLOR_nit__lexer__TKwself__init_tk;
val* NEW_nit__TKwtrue(const struct type* type);
extern const struct type type_nit__TKwtrue;
extern const int COLOR_nit__lexer__TKwtrue__init_tk;
val* NEW_nit__TKwfalse(const struct type* type);
extern const struct type type_nit__TKwfalse;
extern const int COLOR_nit__lexer__TKwfalse__init_tk;
val* NEW_nit__TKwnull(const struct type* type);
extern const struct type type_nit__TKwnull;
extern const int COLOR_nit__lexer__TKwnull__init_tk;
val* NEW_nit__TKwas(const struct type* type);
extern const struct type type_nit__TKwas;
extern const int COLOR_nit__lexer__TKwas__init_tk;
val* NEW_nit__TKwnullable(const struct type* type);
extern const struct type type_nit__TKwnullable;
extern const int COLOR_nit__lexer__TKwnullable__init_tk;
val* NEW_nit__TKwisset(const struct type* type);
extern const struct type type_nit__TKwisset;
extern const int COLOR_nit__lexer__TKwisset__init_tk;
val* NEW_nit__TKwlabel(const struct type* type);
extern const struct type type_nit__TKwlabel;
extern const int COLOR_nit__lexer__TKwlabel__init_tk;
val* NEW_nit__TKwwith(const struct type* type);
extern const struct type type_nit__TKwwith;
extern const int COLOR_nit__lexer__TKwwith__init_tk;
val* NEW_nit__TKwdebug(const struct type* type);
extern const struct type type_nit__TKwdebug;
extern const int COLOR_nit__lexer__TKwdebug__init_tk;
val* NEW_nit__TOpar(const struct type* type);
extern const struct type type_nit__TOpar;
extern const int COLOR_nit__lexer__TOpar__init_tk;
val* NEW_nit__TCpar(const struct type* type);
extern const struct type type_nit__TCpar;
extern const int COLOR_nit__lexer__TCpar__init_tk;
val* NEW_nit__TObra(const struct type* type);
extern const struct type type_nit__TObra;
extern const int COLOR_nit__lexer__TObra__init_tk;
val* NEW_nit__TCbra(const struct type* type);
extern const struct type type_nit__TCbra;
extern const int COLOR_nit__lexer__TCbra__init_tk;
val* NEW_nit__TComma(const struct type* type);
extern const struct type type_nit__TComma;
extern const int COLOR_nit__lexer__TComma__init_tk;
val* NEW_nit__TColumn(const struct type* type);
extern const struct type type_nit__TColumn;
extern const int COLOR_nit__lexer__TColumn__init_tk;
val* NEW_nit__TQuad(const struct type* type);
extern const struct type type_nit__TQuad;
extern const int COLOR_nit__lexer__TQuad__init_tk;
val* NEW_nit__TAssign(const struct type* type);
extern const struct type type_nit__TAssign;
extern const int COLOR_nit__lexer__TAssign__init_tk;
val* NEW_nit__TPluseq(const struct type* type);
extern const struct type type_nit__TPluseq;
extern const int COLOR_nit__lexer__TPluseq__init_tk;
val* NEW_nit__TMinuseq(const struct type* type);
extern const struct type type_nit__TMinuseq;
extern const int COLOR_nit__lexer__TMinuseq__init_tk;
val* NEW_nit__TStareq(const struct type* type);
extern const struct type type_nit__TStareq;
extern const int COLOR_nit__lexer__TStareq__init_tk;
val* NEW_nit__TSlasheq(const struct type* type);
extern const struct type type_nit__TSlasheq;
extern const int COLOR_nit__lexer__TSlasheq__init_tk;
val* NEW_nit__TPercenteq(const struct type* type);
extern const struct type type_nit__TPercenteq;
extern const int COLOR_nit__lexer__TPercenteq__init_tk;
val* NEW_nit__TStarstareq(const struct type* type);
extern const struct type type_nit__TStarstareq;
extern const int COLOR_nit__lexer__TStarstareq__init_tk;
val* NEW_nit__TPipeeq(const struct type* type);
extern const struct type type_nit__TPipeeq;
extern const int COLOR_nit__lexer__TPipeeq__init_tk;
val* NEW_nit__TCareteq(const struct type* type);
extern const struct type type_nit__TCareteq;
extern const int COLOR_nit__lexer__TCareteq__init_tk;
val* NEW_nit__TAmpeq(const struct type* type);
extern const struct type type_nit__TAmpeq;
extern const int COLOR_nit__lexer__TAmpeq__init_tk;
val* NEW_nit__TLleq(const struct type* type);
extern const struct type type_nit__TLleq;
extern const int COLOR_nit__lexer__TLleq__init_tk;
val* NEW_nit__TGgeq(const struct type* type);
extern const struct type type_nit__TGgeq;
extern const int COLOR_nit__lexer__TGgeq__init_tk;
val* NEW_nit__TDotdotdot(const struct type* type);
extern const struct type type_nit__TDotdotdot;
extern const int COLOR_nit__lexer__TDotdotdot__init_tk;
val* NEW_nit__TDotdot(const struct type* type);
extern const struct type type_nit__TDotdot;
extern const int COLOR_nit__lexer__TDotdot__init_tk;
val* NEW_nit__TDot(const struct type* type);
extern const struct type type_nit__TDot;
extern const int COLOR_nit__lexer__TDot__init_tk;
val* NEW_nit__TPlus(const struct type* type);
extern const struct type type_nit__TPlus;
extern const int COLOR_nit__lexer__TPlus__init_tk;
val* NEW_nit__TMinus(const struct type* type);
extern const struct type type_nit__TMinus;
extern const int COLOR_nit__lexer__TMinus__init_tk;
val* NEW_nit__TStar(const struct type* type);
extern const struct type type_nit__TStar;
extern const int COLOR_nit__lexer__TStar__init_tk;
val* NEW_nit__TStarstar(const struct type* type);
extern const struct type type_nit__TStarstar;
extern const int COLOR_nit__lexer__TStarstar__init_tk;
val* NEW_nit__TSlash(const struct type* type);
extern const struct type type_nit__TSlash;
extern const int COLOR_nit__lexer__TSlash__init_tk;
val* NEW_nit__TPercent(const struct type* type);
extern const struct type type_nit__TPercent;
extern const int COLOR_nit__lexer__TPercent__init_tk;
val* NEW_nit__TPipe(const struct type* type);
extern const struct type type_nit__TPipe;
extern const int COLOR_nit__lexer__TPipe__init_tk;
val* NEW_nit__TCaret(const struct type* type);
extern const struct type type_nit__TCaret;
extern const int COLOR_nit__lexer__TCaret__init_tk;
val* NEW_nit__TAmp(const struct type* type);
extern const struct type type_nit__TAmp;
extern const int COLOR_nit__lexer__TAmp__init_tk;
val* NEW_nit__TTilde(const struct type* type);
extern const struct type type_nit__TTilde;
extern const int COLOR_nit__lexer__TTilde__init_tk;
val* NEW_nit__TEq(const struct type* type);
extern const struct type type_nit__TEq;
extern const int COLOR_nit__lexer__TEq__init_tk;
val* NEW_nit__TNe(const struct type* type);
extern const struct type type_nit__TNe;
extern const int COLOR_nit__lexer__TNe__init_tk;
val* NEW_nit__TLt(const struct type* type);
extern const struct type type_nit__TLt;
extern const int COLOR_nit__lexer__TLt__init_tk;
val* NEW_nit__TLe(const struct type* type);
extern const struct type type_nit__TLe;
extern const int COLOR_nit__lexer__TLe__init_tk;
val* NEW_nit__TLl(const struct type* type);
extern const struct type type_nit__TLl;
extern const int COLOR_nit__lexer__TLl__init_tk;
val* NEW_nit__TGt(const struct type* type);
extern const struct type type_nit__TGt;
extern const int COLOR_nit__lexer__TGt__init_tk;
val* NEW_nit__TGe(const struct type* type);
extern const struct type type_nit__TGe;
extern const int COLOR_nit__lexer__TGe__init_tk;
val* NEW_nit__TGg(const struct type* type);
extern const struct type type_nit__TGg;
extern const int COLOR_nit__lexer__TGg__init_tk;
val* NEW_nit__TStarship(const struct type* type);
extern const struct type type_nit__TStarship;
extern const int COLOR_nit__lexer__TStarship__init_tk;
val* NEW_nit__TBang(const struct type* type);
extern const struct type type_nit__TBang;
extern const int COLOR_nit__lexer__TBang__init_tk;
val* NEW_nit__TAt(const struct type* type);
extern const struct type type_nit__TAt;
extern const int COLOR_nit__lexer__TAt__init_tk;
val* NEW_nit__TClassid(const struct type* type);
extern const struct type type_nit__TClassid;
extern const int COLOR_nit__lexer__TClassid__init_tk;
val* NEW_nit__TId(const struct type* type);
extern const struct type type_nit__TId;
extern const int COLOR_nit__lexer__TId__init_tk;
val* NEW_nit__TAttrid(const struct type* type);
extern const struct type type_nit__TAttrid;
extern const int COLOR_nit__lexer__TAttrid__init_tk;
val* NEW_nit__TNumber(const struct type* type);
extern const struct type type_nit__TNumber;
extern const int COLOR_nit__lexer__TNumber__init_tk;
val* NEW_nit__THexNumber(const struct type* type);
extern const struct type type_nit__THexNumber;
extern const int COLOR_nit__lexer__THexNumber__init_tk;
val* NEW_nit__TFloat(const struct type* type);
extern const struct type type_nit__TFloat;
extern const int COLOR_nit__lexer__TFloat__init_tk;
val* NEW_nit__TString(const struct type* type);
extern const struct type type_nit__TString;
extern const int COLOR_nit__lexer__TString__init_tk;
val* NEW_nit__TStartString(const struct type* type);
extern const struct type type_nit__TStartString;
extern const int COLOR_nit__lexer__TStartString__init_tk;
val* NEW_nit__TMidString(const struct type* type);
extern const struct type type_nit__TMidString;
extern const int COLOR_nit__lexer__TMidString__init_tk;
val* NEW_nit__TEndString(const struct type* type);
extern const struct type type_nit__TEndString;
extern const int COLOR_nit__lexer__TEndString__init_tk;
val* NEW_nit__TChar(const struct type* type);
extern const struct type type_nit__TChar;
extern const int COLOR_nit__lexer__TChar__init_tk;
val* NEW_nit__TBadString(const struct type* type);
extern const struct type type_nit__TBadString;
extern const int COLOR_nit__lexer__TBadString__init_tk;
val* NEW_nit__TBadChar(const struct type* type);
extern const struct type type_nit__TBadChar;
extern const int COLOR_nit__lexer__TBadChar__init_tk;
val* NEW_nit__TExternCodeSegment(const struct type* type);
extern const struct type type_nit__TExternCodeSegment;
extern const int COLOR_nit__lexer__TExternCodeSegment__init_tk;
extern const char FILE_nit__lexer[];
