#include "nit.common.h"
extern const int COLOR_nituml__ToolContext___umlphase;
extern const char FILE_nituml[];
extern const int COLOR_nituml__ToolContext___opt_gen;
extern const int COLOR_nit__toolcontext__ToolContext__option_context;
extern const int COLOR_nituml__ToolContext__opt_gen;
val* NEW_standard__Array(const struct type* type);
extern const struct type type_standard__Array__opts__Option;
val* NEW_standard__NativeArray(int length, const struct type* type);
extern const struct type type_standard__NativeArray__opts__Option;
extern const int COLOR_standard__array__Array__with_native;
extern const int COLOR_opts__OptionContext__add_option;
extern const int COLOR_nituml___nit__ToolContext___standard__kernel__Object__init;
val* NEW_standard__FileWriter(const struct type* type);
extern const struct type type_standard__FileWriter;
val* standard___standard__NativeString___to_s_with_length(char* self, long p0);
extern const int COLOR_standard__file__FileWriter__open;
val* NEW_nit__UMLModel(const struct type* type);
extern const struct type type_nit__UMLModel;
extern const int COLOR_nit__model_base__MEntity__model;
extern const int COLOR_nit__phase__Phase__toolcontext;
extern const int COLOR_nit__uml_base__UMLModel__model_61d;
extern const int COLOR_nit__uml_base__UMLModel__mainmodule_61d;
extern const int COLOR_nit__uml_base__UMLModel__ctx_61d;
extern const int COLOR_standard__kernel__Object__init;
extern const int COLOR_opts__Option__value;
extern const int COLOR_nit__uml_class__UMLModel__generate_class_uml;
extern const int COLOR_standard__stream__Writable__write_to_string;
extern const int COLOR_standard__file__Object__print;
extern const int COLOR_standard__stream__Writer__write;
extern const int COLOR_nit__uml_module__UMLModel__generate_package_uml;
extern const int COLOR_standard__stream__Stream__close;
val* NEW_nit__ToolContext(const struct type* type);
extern const struct type type_nit__ToolContext;
extern const int COLOR_standard__string__Object__args;
extern const int COLOR_nit__toolcontext__ToolContext__process_options;
extern const int COLOR_opts__OptionContext__rest;
val* NEW_nit__Model(const struct type* type);
extern const struct type type_nit__Model;
val* NEW_nit__ModelBuilder(const struct type* type);
extern const struct type type_nit__ModelBuilder;
extern const int COLOR_nit__modelbuilder_base__ModelBuilder__model_61d;
extern const int COLOR_nit__modelbuilder_base__ModelBuilder__toolcontext_61d;
extern const int COLOR_nit__loader__ModelBuilder__parse_full;
extern const int COLOR_standard__abstract_collection__Collection__is_empty;
extern const int COLOR_nit__modelbuilder__ModelBuilder__run_phases;
extern const int COLOR_nit__modelbuilder__ToolContext__run_global_phases;
