#include "nit.common.h"
extern const int COLOR_standard__kernel__Object___61d_61d;
extern const int COLOR_standard__kernel__Object__object_id;
extern const struct type type_standard__Int;
extern const char FILE_standard__kernel[];
extern const int COLOR_standard__kernel__Sys__main;
#include "kernel_nit.h"
extern const int COLOR_standard__kernel__Comparable__OTHER;
extern const int COLOR_standard__kernel__Comparable___60d;
extern const int COLOR_standard__kernel__Comparable___60d_61d;
extern const int COLOR_standard__kernel__Comparable___62d;
extern const int COLOR_standard__kernel__Discrete__successor;
extern const int COLOR_standard__kernel__Numeric__zero;
long standard___standard__Bool___to_i(short int self);
long standard___standard__Bool___Object__hash(short int self);
extern const struct class class_standard__Float;
extern const struct type type_standard__Float;
val* BOX_standard__Float(double);
double standard___standard__Float___Numeric__to_f(double self);
double standard___standard__Float___Numeric__zero(double self);
extern const int COLOR_standard__kernel__Numeric__to_f;
double standard___standard__Float___Numeric__value_of(double self, val* p0);
long standard___standard__Float___Comparable___60d_61d_62d(double self, double p0);
short int standard___standard__Float___Comparable__is_between(double self, double p0, double p1);
double standard___standard__Float___Comparable__max(double self, double p0);
double standard___standard__Float___Comparable__min(double self, double p0);
long standard___standard__Int___Discrete__successor(long self, long p0);
long standard___standard__Int___Discrete__predecessor(long self, long p0);
long standard___standard__Int___Object__hash(long self);
long standard___standard__Int___Numeric__zero(long self);
extern const int COLOR_standard__kernel__Numeric__to_i;
long standard___standard__Int___Numeric__value_of(long self, val* p0);
long standard___standard__Int___Numeric__to_i(long self);
long standard___standard__Int___Discrete__distance(long self, long p0);
long standard___standard__Int___Comparable___60d_61d_62d(long self, long p0);
short int standard___standard__Int___Comparable__is_between(long self, long p0, long p1);
long standard___standard__Int___Comparable__max(long self, long p0);
long standard___standard__Int___Comparable__min(long self, long p0);
long standard___standard__Int___digit_count_base_95d10(long self);
long standard___standard__Char___Object__hash(char self);
extern const struct type type_standard__Char;
long standard___standard__Char___Discrete__distance(char self, char p0);
short int standard___standard__Char___is_digit(char self);
char standard___standard__Char___to_lower(char self);
short int standard___standard__Char___is_upper(char self);
short int standard___standard__Char___is_lower(char self);
