#include "nit.common.h"
val* BOX_standard__Pointer(void*);
extern const struct type type_standard__re__NativeRegex;
extern const struct class class_standard__re__NativeRegex;
void* re___new_NativeRegex_malloc___impl(  );
long re___NativeRegex_regcomp___impl( void* recv, char* regex, long cflags );
long re___NativeRegex_regexec___impl( void* recv, char* string, long nmatch, void* pmatch, long eflags );
long re___NativeRegex_regexec_match_only___impl( void* recv, char* string, long eflags );
void re___NativeRegex_regfree___impl( void* recv );
char* re___NativeRegex_regerror___impl( void* recv, long errcode );
long re___NativeRegex_re_nsub___impl( void* recv );
int re___Int_is_nomatch___impl( long recv );
extern const struct type type_standard__re__NativeMatchArray;
extern const struct class class_standard__re__NativeMatchArray;
void* re___new_NativeMatchArray_malloc___impl( long length );
long re___NativeMatchArray_rm_so___impl( void* recv );
long re___NativeMatchArray_rm_eo___impl( void* recv );
void* re___NativeMatchArray__index___impl( void* recv, long index );
char* re___NativeString_substring_from___impl( char* recv, long index );
val* NEW_standard__Regex(const struct type* type);
extern const struct type type_standard__Regex;
extern const int COLOR_standard__string__Object__to_s;
extern const int COLOR_standard__re__Regex__string_61d;
extern const int COLOR_standard__kernel__Object__init;
extern const int COLOR_standard__re__Regex___string;
extern const char FILE_standard__re[];
extern const int COLOR_standard__re__Regex___extended;
extern const int COLOR_standard__re__Regex___ignore_case;
extern const int COLOR_standard__re__Regex___optimize_is_in;
extern const int COLOR_standard__re__Regex___newline;
extern const int COLOR_standard__re__Regex___not_bol;
extern const int COLOR_standard__re__Regex___not_eol;
extern const int COLOR_standard__re__Regex___native;
extern const int COLOR_standard__re__Regex___native_match;
extern const int COLOR_standard__re__Regex__native_match_is_init_61d;
val* NEW_standard__re__NativeMatchArray(const struct type* type);
extern const int COLOR_standard__re__Regex__native;
extern const int COLOR_standard__re__NativeRegex__re_nsub;
extern const struct type type_standard__Int;
extern const char FILE_standard__kernel[];
extern const int COLOR_standard__re__NativeMatchArray__malloc;
extern const int COLOR_standard__re__Regex___native_match_is_init;
extern const int COLOR_standard__re__Regex___cflags_cache;
extern const int COLOR_standard__re__Regex___string_cache;
extern const int COLOR_standard__re__Regex__extended;
extern const int COLOR_standard__re__Sys__flag_extended;
long standard__math___Int___bin_or(long self, long p0);
extern const int COLOR_standard__re__Regex__ignore_case;
extern const int COLOR_standard__re__Sys__flag_icase;
extern const int COLOR_standard__re__Regex__optimize_is_in;
extern const int COLOR_standard__re__Sys__flag_nosub;
extern const int COLOR_standard__re__Regex__newline;
extern const int COLOR_standard__re__Sys__flag_newline;
extern const int COLOR_standard__kernel__Object___61d_61d;
extern const int COLOR_standard__re__Regex__cflags_cache;
extern const int COLOR_standard__re__Regex__string;
extern const int COLOR_standard__re__Regex__string_cache;
extern const int COLOR_standard__kernel__Object___33d_61d;
val* NEW_standard__re__NativeRegex(const struct type* type);
extern const int COLOR_standard__re__NativeRegex__malloc;
extern const int COLOR_standard__re__Regex__native_61d;
extern const int COLOR_standard__string__Text__to_cstring;
extern const int COLOR_standard__re__NativeRegex__regcomp;
extern const int COLOR_standard__re__Regex__cflags_cache_61d;
extern const int COLOR_standard__re__Regex__string_cache_61d;
extern const int COLOR_standard__re__NativeRegex__regerror;
val* standard___standard__NativeString___to_s_with_copy(char* self);
void standard___standard__Pointer___free(val* self);
val* NEW_standard__Error(const struct type* type);
extern const struct type type_standard__Error;
extern const int COLOR_standard__error__Error__message_61d;
extern const int COLOR_standard__re__NativeRegex__regfree;
extern const int COLOR_standard__kernel__Pointer__free;
extern const int COLOR_standard__re__Regex__native_match_is_init;
extern const int COLOR_standard__re__Regex__native_match;
extern const int COLOR_standard__re__Regex__not_bol;
extern const int COLOR_standard__re__Sys__flag_notbol;
extern const int COLOR_standard__re__Regex__not_eol;
extern const int COLOR_standard__re__Sys__flag_noteol;
extern const int COLOR_standard__re__Regex__compile;
val* NEW_standard__NativeArray(int length, const struct type* type);
extern const struct type type_standard__NativeArray__standard__String;
val* standard___standard__NativeString___to_s_with_length(char* self, long p0);
extern const int COLOR_standard__error__Error__message;
extern const int COLOR_standard__string__NativeArray__native_to_s;
extern const int COLOR_standard__kernel__Object__output;
extern const int COLOR_standard__re__Regex__gather_eflags;
extern const int COLOR_standard__re__NativeRegex__regexec_match_only;
short int standard__re___Int___is_nomatch(long self);
extern const int COLOR_standard__re__Regex__get_error;
extern const int COLOR_standard__string__Text__substring_from;
extern const int COLOR_standard__re__NativeRegex__regexec;
extern const int COLOR_standard__re__NativeMatchArray__rm_so;
val* NEW_standard__Match(const struct type* type);
extern const struct type type_standard__Match;
extern const int COLOR_standard__re__NativeMatchArray__rm_eo;
extern const int COLOR_standard__string_search__Match__string_61d;
extern const int COLOR_standard__string_search__Match__from_61d;
extern const int COLOR_standard__string_search__Match__length_61d;
extern const int COLOR_standard__re__Match__subs;
extern const int COLOR_standard__re__NativeMatchArray___91d_93d;
extern const int COLOR_standard__abstract_collection__SimpleCollection__add;
long standard___standard__Int___Discrete__successor(long self, long p0);
val* NEW_standard__Array(const struct type* type);
extern const struct type type_standard__Array__standard__Match;
char* standard__re___NativeString___substring_from(char* self, long p0);
extern const int COLOR_standard___standard__Regex___standard__kernel__Object__init;
extern const int COLOR_standard__re__Match___subs;
extern const int COLOR_standard__abstract_collection__Collection__length;
extern const int COLOR_standard__abstract_collection__SequenceRead___91d_93d;
long re___Sys_flag_extended___impl( struct nitni_instance * recv );
long re___Sys_flag_icase___impl( struct nitni_instance * recv );
long re___Sys_flag_nosub___impl( struct nitni_instance * recv );
long re___Sys_flag_newline___impl( struct nitni_instance * recv );
long re___Sys_flag_notbol___impl( struct nitni_instance * recv );
long re___Sys_flag_noteol___impl( struct nitni_instance * recv );
long re___Sys_error_nomatch___impl( struct nitni_instance * recv );
long re___Sys_error_espace___impl( struct nitni_instance * recv );
