#include "nit.common.h"
int posix___Sys_uid__assign___impl( struct nitni_instance * recv, long uid );
long posix___Sys_uid___impl( struct nitni_instance * recv );
int posix___Sys_gid__assign___impl( struct nitni_instance * recv, long gid );
long posix___Sys_gid___impl( struct nitni_instance * recv );
int posix___Sys_euid__assign___impl( struct nitni_instance * recv, long uid );
long posix___Sys_euid___impl( struct nitni_instance * recv );
int posix___Sys_egid__assign___impl( struct nitni_instance * recv, long gid );
long posix___Sys_egid___impl( struct nitni_instance * recv );
void* posix___new_Passwd_from_uid___impl( long uid );
void* posix___new_Passwd_from_name___impl( struct nitni_instance * name );
extern const int COLOR_standard__string__Text__to_cstring;
struct nitni_instance * posix___Passwd_name___impl( void* recv );
val* standard___standard__NativeString___Object__to_s(char* self);
struct nitni_instance * posix___Passwd_passwd___impl( void* recv );
long posix___Passwd_uid___impl( void* recv );
long posix___Passwd_gid___impl( void* recv );
struct nitni_instance * posix___Passwd_dir___impl( void* recv );
struct nitni_instance * posix___Passwd_shell___impl( void* recv );
void* posix___new_Group_from_gid___impl( long gid );
void* posix___new_Group_from_name___impl( struct nitni_instance * name );
struct nitni_instance * posix___Group_name___impl( void* recv );
struct nitni_instance * posix___Group_passwd___impl( void* recv );
long posix___Group_gid___impl( void* recv );
struct nitni_instance * posix___Group_mem___impl( void* recv );
val* NEW_standard__Array(const struct type* type);
extern const struct type type_standard__Array__standard__String;
extern const int COLOR_standard__kernel__Object__init;
extern const int COLOR_standard__abstract_collection__SimpleCollection__add;
