#include "nit.common.h"
extern const int COLOR_standard__error__Error___message;
extern const char FILE_standard__error[];
extern const int COLOR_standard__error__Error___cause;
extern const int COLOR_standard__error__Error__message;
extern const int COLOR_standard___standard__Error___standard__kernel__Object__init;
extern const int COLOR_standard__error__MaybeError___maybe_value;
extern const int COLOR_nullable__standard__MaybeError___35dV;
extern const int COLOR_standard__error__MaybeError___maybe_error;
extern const int COLOR_nullable__standard__MaybeError___35dE;
extern const int COLOR_standard__error__MaybeError__maybe_error;
extern const int COLOR_standard__kernel__Object___33d_61d;
extern const int COLOR_standard__error__MaybeError__maybe_value;
extern const int COLOR_standard__MaybeError___35dV;
extern const int COLOR_standard__MaybeError___35dE;
extern const int COLOR_standard__string__Object__to_s;
extern const int COLOR_standard__error__MaybeError__value;
extern const int COLOR_standard___standard__MaybeError___standard__kernel__Object__init;
